/**
 * Per-county data for Oklahoma county landing pages.
 *
 * Source notes:
 * - Populations pulled from existing static county pages (2024 estimates).
 * - Courthouse addresses verified against county .gov / okcounties.org where
 *   a bug was discovered in the static files (see CORRECTIONS below).
 * - heroLead is a 2-3 sentence production lead written for every county.
 *   Phase 2 will replace per-county heroLeads with swarm-verified unique
 *   prose; the current leads are deliberately formulaic but county-specific
 *   (seat + county name + no pricing, no em-dashes).
 *
 * KNOWN CORRECTIONS applied (bugs that existed in static files):
 * - Love County: was "301 N Broadway St, Walters" (Cotton County's seat).
 *                Corrected to 405 W Main St, Marietta, OK 73448.
 * - Kay County:  was "300 Courthouse Dr, Perry" (Noble County's seat).
 *                Corrected to 201 S Main St, Newkirk, OK 74647.
 * - Kiowa County: was "315 SW 5th St, Lawton" (Comanche County's seat).
 *                 Corrected to 316 S Main St, Hobart, OK 73651.
 * - McIntosh County: was "222 E Dewey Ave, Sapulpa" (Creek County's seat).
 *                    Corrected to 110 N 1st St, Eufaula, OK 74432.
 *
 * VERIFY markers flag addresses that were written as "Courthouse, <city>"
 * in the source files (no street) and still need a verified street address
 * from the swarm.
 */

export interface CountyDatum {
  slug: string;
  countyName: string;
  countySeat: string;
  population?: number;
  courthouseAddress?: string;
  heroLead: string;
}

const lead = (countyName: string, seat: string, extra?: string): string => {
  const base = `Licensed and bonded process server covering ${countyName}, Oklahoma, from the ${seat} county seat to every town and rural route in the county. We deliver summons, subpoenas, evictions, and civil documents with GPS-verified attempts and notarized affidavits ready for filing.`;
  const tail = ` Standard, rush, and same-day service tiers are available; see current rates on our pricing page or call (539) 367-6832 to schedule.`;
  return extra ? `${base} ${extra}${tail}` : `${base}${tail}`;
};

export const COUNTIES: Record<string, CountyDatum> = {
  'adair-county': { slug: 'adair-county', countyName: 'Adair County', countySeat: 'Stilwell', population: 19495, courthouseAddress: '220 W Division St, Stilwell, OK 74960', heroLead: lead('Adair County', 'Stilwell', 'We cover Stilwell, Westville, Watts, and rural routes across Cherokee Nation reservation territory in far eastern Oklahoma.') },
  'alfalfa-county': { slug: 'alfalfa-county', countyName: 'Alfalfa County', countySeat: 'Cherokee', population: 5810, courthouseAddress: '300 S Grand Ave, Cherokee, OK 73728', heroLead: lead('Alfalfa County', 'Cherokee', 'We cover Cherokee, Helena, Jet, Carmen, and rural farmland across this northwest Oklahoma wheat-country county.') },
  'atoka-county': { slug: 'atoka-county', countyName: 'Atoka County', countySeat: 'Atoka', population: 14143, courthouseAddress: '200 E Court St, Atoka, OK 74525', heroLead: lead('Atoka County', 'Atoka', 'We cover Atoka, Stringtown, Caney, Tushka, and the Muddy Boggy River communities along US-69 in southeastern Oklahoma.') },
  'beaver-county': { slug: 'beaver-county', countyName: 'Beaver County', countySeat: 'Beaver', population: 5049, courthouseAddress: '111 W 2nd St, Beaver, OK 73932', heroLead: lead('Beaver County', 'Beaver', 'We cover Beaver, Forgan, Balko, Turpin, and the ranchland of the Oklahoma Panhandle.') },
  'beckham-county': { slug: 'beckham-county', countyName: 'Beckham County', countySeat: 'Sayre', population: 16292, courthouseAddress: '302 E Main St, Sayre, OK 73662', heroLead: lead('Beckham County', 'Sayre', 'We cover Sayre, Elk City, Erick, and the I-40 and Route 66 corridor across western Oklahoma.') },
  'blaine-county': { slug: 'blaine-county', countyName: 'Blaine County', countySeat: 'Watonga', population: 8735, courthouseAddress: '212 N Weigle Ave, Watonga, OK 73772', heroLead: lead('Blaine County', 'Watonga', 'We cover Watonga, Okeene, Canton, Geary, and the Cheyenne-Arapaho jurisdiction areas of west-central Oklahoma.') },
  'bryan-county': { slug: 'bryan-county', countyName: 'Bryan County', countySeat: 'Durant', population: 47498, courthouseAddress: '402 W Evergreen St, Durant, OK 74701', heroLead: lead('Bryan County', 'Durant', 'We cover Durant, Calera, Caddo, Colbert, and the Choctaw Nation headquarters region along the Red River border with Texas.') },
  'caddo-county': { slug: 'caddo-county', countyName: 'Caddo County', countySeat: 'Anadarko', population: 26945, courthouseAddress: '201 W Oklahoma Ave, Anadarko, OK 73005', heroLead: lead('Caddo County', 'Anadarko', 'We cover Anadarko, Hinton, Fort Cobb, Carnegie, and the many tribal headquarters located across this county.') },
  'canadian-county': { slug: 'canadian-county', countyName: 'Canadian County', countySeat: 'El Reno', population: 154943, courthouseAddress: '201 N Choctaw Ave, El Reno, OK 73036', heroLead: lead('Canadian County', 'El Reno', 'We cover El Reno, Mustang, Yukon, Piedmont, and the fast-growing OKC suburban corridor, Oklahoma\u2019s fastest-growing county.') },
  'carter-county': { slug: 'carter-county', countyName: 'Carter County', countySeat: 'Ardmore', population: 48498, courthouseAddress: '20 B St SW, Ardmore, OK 73401', heroLead: lead('Carter County', 'Ardmore', 'We cover Ardmore, Lone Grove, Wilson, Healdton, and the I-35 corridor through southern Oklahoma.') },
  'cherokee-county': { slug: 'cherokee-county', countyName: 'Cherokee County', countySeat: 'Tahlequah', population: 46007, courthouseAddress: '213 W Delaware St, Tahlequah, OK 74464', heroLead: lead('Cherokee County', 'Tahlequah', 'We cover Tahlequah, the Cherokee Nation capital, plus Hulbert, Welling, Keys, and Lake Tenkiller shoreline properties.') },
  'choctaw-county': { slug: 'choctaw-county', countyName: 'Choctaw County', countySeat: 'Hugo', population: 14204, courthouseAddress: '300 E Duke St, Hugo, OK 74743', heroLead: lead('Choctaw County', 'Hugo', 'We cover Hugo, Fort Towson, Boswell, Soper, and the Kiamichi River communities of southeastern Oklahoma.') },
  'cimarron-county': { slug: 'cimarron-county', countyName: 'Cimarron County', countySeat: 'Boise City', population: 2269, courthouseAddress: 'Courthouse Square, Boise City, OK 73933', heroLead: lead('Cimarron County', 'Boise City', 'We cover Boise City, Kenton, Keyes, and the far western tip of the Oklahoma Panhandle\u2014the only U.S. county bordering four other states.') },
  'cleveland-county': { slug: 'cleveland-county', countyName: 'Cleveland County', countySeat: 'Norman', population: 295532, courthouseAddress: '200 S Peters Ave, Norman, OK 73069', heroLead: lead('Cleveland County', 'Norman', 'We cover Norman, Moore, Noble, and the University of Oklahoma and I-35 corridor south of Oklahoma City.') },
  'coal-county': { slug: 'coal-county', countyName: 'Coal County', countySeat: 'Coalgate', population: 5266, courthouseAddress: '4 N Main St, Coalgate, OK 74538', heroLead: lead('Coal County', 'Coalgate', 'We cover Coalgate, Tupelo, Lehigh, and the small-town ranching communities of south-central Oklahoma.') },
  'comanche-county': { slug: 'comanche-county', countyName: 'Comanche County', countySeat: 'Lawton', population: 125543, courthouseAddress: '315 SW 5th St, Lawton, OK 73501', heroLead: lead('Comanche County', 'Lawton', 'We cover Lawton, Cache, Fletcher, Elgin, plus Fort Sill and the Wichita Mountains region of southwestern Oklahoma.') },
  'cotton-county': { slug: 'cotton-county', countyName: 'Cotton County', countySeat: 'Walters', population: 5527, courthouseAddress: '301 N Broadway St, Walters, OK 73572', heroLead: lead('Cotton County', 'Walters', 'We cover Walters, Temple, Randlett, Devol, and the Red River border communities of southwestern Oklahoma.') },
  'craig-county': { slug: 'craig-county', countyName: 'Craig County', countySeat: 'Vinita', population: 14207, courthouseAddress: '301 W Canadian Ave, Vinita, OK 74301', heroLead: lead('Craig County', 'Vinita', 'We cover Vinita, Big Cabin, Welch, Bluejacket, and the Route 66 and I-44 crossroads of northeastern Oklahoma.') },
  'creek-county': { slug: 'creek-county', countyName: 'Creek County', countySeat: 'Sapulpa', population: 72639, courthouseAddress: '317 E Lee Ave, Sapulpa, OK 74066', heroLead: lead('Creek County', 'Sapulpa', 'We cover Sapulpa, Bristow, Kellyville, Kiefer, Mounds, Mannford, and the western Tulsa metro communities along Route 66.') },
  'custer-county': { slug: 'custer-county', countyName: 'Custer County', countySeat: 'Arapaho', population: 30814, courthouseAddress: '603 B St, Arapaho, OK 73620', heroLead: lead('Custer County', 'Arapaho', 'We cover Arapaho, Weatherford, Clinton, Thomas, and the I-40 corridor across west-central Oklahoma.') },
  'delaware-county': { slug: 'delaware-county', countyName: 'Delaware County', countySeat: 'Jay', population: 43081, courthouseAddress: '327 S 5th St, Jay, OK 74346', heroLead: lead('Delaware County', 'Jay', 'We cover Jay, Grove, Kansas, Colcord, and Grand Lake shoreline properties across Cherokee Nation territory in far northeastern Oklahoma.') },
  'dewey-county': { slug: 'dewey-county', countyName: 'Dewey County', countySeat: 'Taloga', population: 4484, courthouseAddress: 'Ruble and Broadway, Taloga, OK 73667', heroLead: lead('Dewey County', 'Taloga', 'We cover Taloga, Seiling, Leedey, Vici, and the ranchland of northwestern Oklahoma.') },
  'ellis-county': { slug: 'ellis-county', countyName: 'Ellis County', countySeat: 'Arnett', population: 3909, courthouseAddress: 'Courthouse Square, Arnett, OK 73832', heroLead: lead('Ellis County', 'Arnett', 'We cover Arnett, Shattuck, Gage, Fargo, and the Panhandle-adjacent ranchland of far northwestern Oklahoma.') },
  'garfield-county': { slug: 'garfield-county', countyName: 'Garfield County', countySeat: 'Enid', population: 62536, courthouseAddress: '114 W Broadway Ave, Enid, OK 73701', heroLead: lead('Garfield County', 'Enid', 'We cover Enid, Waukomis, Fairmont, Kremlin, and the wheat-and-oil country of north-central Oklahoma.') },
  'garvin-county': { slug: 'garvin-county', countyName: 'Garvin County', countySeat: 'Pauls Valley', population: 25757, courthouseAddress: '201 W Grant Ave, Pauls Valley, OK 73075', heroLead: lead('Garvin County', 'Pauls Valley', 'We cover Pauls Valley, Maysville, Wynnewood, Elmore City, and the I-35 corridor south of Oklahoma City.') },
  'grady-county': { slug: 'grady-county', countyName: 'Grady County', countySeat: 'Chickasha', population: 52582, courthouseAddress: '328 W Choctaw Ave, Chickasha, OK 73018', heroLead: lead('Grady County', 'Chickasha', 'We cover Chickasha, Tuttle, Minco, Rush Springs, and the rapidly growing southern OKC metro corridor.') },
  'grant-county': { slug: 'grant-county', countyName: 'Grant County', countySeat: 'Medford', population: 4331, courthouseAddress: '112 E Guthrie St, Medford, OK 73759', heroLead: lead('Grant County', 'Medford', 'We cover Medford, Pond Creek, Deer Creek, Lamont, and the Kansas border wheat country of north-central Oklahoma.') },
  'greer-county': { slug: 'greer-county', countyName: 'Greer County', countySeat: 'Mangum', population: 5586, courthouseAddress: '106 E Jefferson St, Mangum, OK 73554', heroLead: lead('Greer County', 'Mangum', 'We cover Mangum, Granite, Willow, and the Quartz Mountain area of southwestern Oklahoma.') },
  'harmon-county': { slug: 'harmon-county', countyName: 'Harmon County', countySeat: 'Hollis', population: 2409, courthouseAddress: '114 W Hollis St, Hollis, OK 73550', heroLead: lead('Harmon County', 'Hollis', 'We cover Hollis, Gould, Vinson, and the Texas border ranchland of far southwestern Oklahoma.') },
  'harper-county': { slug: 'harper-county', countyName: 'Harper County', countySeat: 'Buffalo', population: 3440, courthouseAddress: '311 SE 1st St, Buffalo, OK 73834', heroLead: lead('Harper County', 'Buffalo', 'We cover Buffalo, Laverne, May, and the Panhandle-adjacent ranchland of northwestern Oklahoma.') },
  'haskell-county': { slug: 'haskell-county', countyName: 'Haskell County', countySeat: 'Stigler', population: 12281, courthouseAddress: '202 E Main St, Stigler, OK 74462', heroLead: lead('Haskell County', 'Stigler', 'We cover Stigler, Kinta, Keota, McCurtain, and the Arkansas River and Lake Eufaula communities of eastern Oklahoma.') },
  'hughes-county': { slug: 'hughes-county', countyName: 'Hughes County', countySeat: 'Holdenville', population: 13021, courthouseAddress: '200 N Broadway St, Holdenville, OK 74848', heroLead: lead('Hughes County', 'Holdenville', 'We cover Holdenville, Wetumka, Calvin, Atwood, and the small-town communities of east-central Oklahoma.') },
  'jackson-county': { slug: 'jackson-county', countyName: 'Jackson County', countySeat: 'Altus', population: 26146, courthouseAddress: '101 N Main St, Altus, OK 73521', heroLead: lead('Jackson County', 'Altus', 'We cover Altus, Blair, Duke, Olustee, and Altus Air Force Base in far southwestern Oklahoma.') },
  'jefferson-county': { slug: 'jefferson-county', countyName: 'Jefferson County', countySeat: 'Waurika', population: 5337, courthouseAddress: '220 N Main St, Waurika, OK 73573', heroLead: lead('Jefferson County', 'Waurika', 'We cover Waurika, Ringling, Ryan, Terral, and the Red River border communities of south-central Oklahoma.') },
  'johnston-county': { slug: 'johnston-county', countyName: 'Johnston County', countySeat: 'Tishomingo', population: 10957, courthouseAddress: '414 W Main St, Tishomingo, OK 73460', heroLead: lead('Johnston County', 'Tishomingo', 'We cover Tishomingo, Mill Creek, Ravia, Milburn, and the Chickasaw Nation tribal headquarters region of south-central Oklahoma.') },
  'kay-county': { slug: 'kay-county', countyName: 'Kay County', countySeat: 'Newkirk', population: 43705, courthouseAddress: '201 S Main St, Newkirk, OK 74647', heroLead: lead('Kay County', 'Newkirk', 'We cover Newkirk, Ponca City, Blackwell, Tonkawa, and the Kansas border communities of north-central Oklahoma.') },
  'kingfisher-county': { slug: 'kingfisher-county', countyName: 'Kingfisher County', countySeat: 'Kingfisher', population: 15184, courthouseAddress: '101 S Main St, Kingfisher, OK 73750', heroLead: lead('Kingfisher County', 'Kingfisher', 'We cover Kingfisher, Hennessey, Okarche, Cashion, and the US-81 and Chisholm Trail corridor of central Oklahoma.') },
  'kiowa-county': { slug: 'kiowa-county', countyName: 'Kiowa County', countySeat: 'Hobart', population: 8509, courthouseAddress: '316 S Main St, Hobart, OK 73651', heroLead: lead('Kiowa County', 'Hobart', 'We cover Hobart, Snyder, Lone Wolf, Mountain View, and the Kiowa-Comanche-Apache tribal jurisdiction of southwestern Oklahoma.') },
  'latimer-county': { slug: 'latimer-county', countyName: 'Latimer County', countySeat: 'Wilburton', population: 9742, courthouseAddress: '109 N Central Ave, Wilburton, OK 74578', heroLead: lead('Latimer County', 'Wilburton', 'We cover Wilburton, Red Oak, Wilburton, and the Sans Bois Mountains and Eastern Oklahoma State College area.') },
  'leflore-county': { slug: 'leflore-county', countyName: 'Le Flore County', countySeat: 'Poteau', population: 48129, courthouseAddress: '100 S Broadway St, Poteau, OK 74953', heroLead: lead('Le Flore County', 'Poteau', 'We cover Poteau, Heavener, Spiro, Pocola, and the Arkansas border and Ouachita Mountain communities of eastern Oklahoma.') },
  'lincoln-county': { slug: 'lincoln-county', countyName: 'Lincoln County', countySeat: 'Chandler', population: 33688, courthouseAddress: '811 Manvel Ave, Chandler, OK 74834', heroLead: lead('Lincoln County', 'Chandler', 'We cover Chandler, Stroud, Prague, Meeker, and the Route 66 corridor between Tulsa and Oklahoma City.') },
  'logan-county': { slug: 'logan-county', countyName: 'Logan County', countySeat: 'Guthrie', population: 50715, courthouseAddress: '301 E Harrison Ave, Guthrie, OK 73044', heroLead: lead('Logan County', 'Guthrie', 'We cover Guthrie, Crescent, Coyle, Mulhall, and the fast-growing northern OKC metro corridor.') },
  'love-county': { slug: 'love-county', countyName: 'Love County', countySeat: 'Marietta', population: 10146, courthouseAddress: '405 W Main St, Marietta, OK 73448', heroLead: lead('Love County', 'Marietta', 'We cover Marietta, Thackerville, Leon, Burneyville, plus the WinStar World Casino complex and the Red River border with Texas.') },
  'major-county': { slug: 'major-county', countyName: 'Major County', countySeat: 'Fairview', population: 7629, courthouseAddress: '500 E Broadway St, Fairview, OK 73737', heroLead: lead('Major County', 'Fairview', 'We cover Fairview, Ringwood, Cleo Springs, Meno, and the wheat country of northwestern Oklahoma.') },
  'marshall-county': { slug: 'marshall-county', countyName: 'Marshall County', countySeat: 'Madill', population: 15312, courthouseAddress: '1 County Courthouse, Madill, OK 73446', heroLead: lead('Marshall County', 'Madill', 'We cover Madill, Kingston, Enos, and Lake Texoma shoreline properties in south-central Oklahoma.') },
  'mayes-county': { slug: 'mayes-county', countyName: 'Mayes County', countySeat: 'Pryor', population: 39046, courthouseAddress: '1 Courthouse Sq, Pryor, OK 74361', heroLead: lead('Mayes County', 'Pryor', 'We cover Pryor, Chouteau, Locust Grove, Salina, Spavinaw, and the MidAmerica Industrial Park and Grand Lake region.') },
  'mcclain-county': { slug: 'mcclain-county', countyName: 'McClain County', countySeat: 'Purcell', population: 41136, courthouseAddress: '121 N 2nd Ave, Purcell, OK 73080', heroLead: lead('McClain County', 'Purcell', 'We cover Purcell, Blanchard, Newcastle, Washington, and the fast-growing southern OKC metro corridor along I-35.') },
  'mccurtain-county': { slug: 'mccurtain-county', countyName: 'McCurtain County', countySeat: 'Idabel', population: 30814, courthouseAddress: '108 N Central Ave, Idabel, OK 74745', heroLead: lead('McCurtain County', 'Idabel', 'We cover Idabel, Broken Bow, Hochatown, Valliant, and the Broken Bow Lake and Beavers Bend State Park tourism corridor.') },
  'mcintosh-county': { slug: 'mcintosh-county', countyName: 'McIntosh County', countySeat: 'Eufaula', population: 18941, courthouseAddress: '110 N 1st St, Eufaula, OK 74432', heroLead: lead('McIntosh County', 'Eufaula', 'We cover Eufaula, Checotah, Hanna, Stidham, and Lake Eufaula shoreline properties across east-central Oklahoma.') },
  'murray-county': { slug: 'murray-county', countyName: 'Murray County', countySeat: 'Sulphur', population: 13904, courthouseAddress: '1001 W Wyandotte Ave, Sulphur, OK 73086', heroLead: lead('Murray County', 'Sulphur', 'We cover Sulphur, Davis, Dougherty, and the Chickasaw National Recreation Area and Arbuckle Mountains tourism region.') },
  'muskogee-county': { slug: 'muskogee-county', countyName: 'Muskogee County', countySeat: 'Muskogee', population: 66553, courthouseAddress: '220 State St, Muskogee, OK 74401', heroLead: lead('Muskogee County', 'Muskogee', 'We cover Muskogee, Fort Gibson, Warner, Haskell, and the Muscogee (Creek) Nation tribal headquarters region of eastern Oklahoma.') },
  'noble-county': { slug: 'noble-county', countyName: 'Noble County', countySeat: 'Perry', population: 10924, courthouseAddress: '300 Courthouse Dr, Perry, OK 73077', heroLead: lead('Noble County', 'Perry', 'We cover Perry, Morrison, Billings, Red Rock, and the I-35 corridor of north-central Oklahoma.') },
  'nowata-county': { slug: 'nowata-county', countyName: 'Nowata County', countySeat: 'Nowata', population: 9320, courthouseAddress: '229 N Maple St, Nowata, OK 74048', heroLead: lead('Nowata County', 'Nowata', 'We cover Nowata, Delaware, Wann, Lenapah, and the Kansas border and Oologah Lake communities of northeastern Oklahoma.') },
  'okfuskee-county': { slug: 'okfuskee-county', countyName: 'Okfuskee County', countySeat: 'Okemah', population: 11310, courthouseAddress: '3rd and Atlanta St, Okemah, OK 74859', heroLead: lead('Okfuskee County', 'Okemah', 'We cover Okemah, Boley, Paden, Weleetka, and the I-40 corridor of east-central Oklahoma.') },
  'oklahoma-county': { slug: 'oklahoma-county', countyName: 'Oklahoma County', countySeat: 'Oklahoma City', population: 796765, courthouseAddress: '321 Park Ave, Oklahoma City, OK 73102', heroLead: lead('Oklahoma County', 'Oklahoma City', 'We cover Oklahoma City, Edmond, Midwest City, Del City, Bethany, and the state capital metro\u2014the most populous county in Oklahoma.') },
  'okmulgee-county': { slug: 'okmulgee-county', countyName: 'Okmulgee County', countySeat: 'Okmulgee', population: 36706, courthouseAddress: '314 W 7th St, Okmulgee, OK 74447', heroLead: lead('Okmulgee County', 'Okmulgee', 'We cover Okmulgee, Henryetta, Beggs, Morris, and the Muscogee (Creek) Nation capital region south of Tulsa.') },
  'osage-county': { slug: 'osage-county', countyName: 'Osage County', countySeat: 'Pawhuska', population: 45818, courthouseAddress: '600 Grandview Ave, Pawhuska, OK 74056', heroLead: lead('Osage County', 'Pawhuska', 'We cover Pawhuska, Skiatook, Hominy, Fairfax, Barnsdall, and the Osage Nation Reservation, Oklahoma\u2019s largest county by area at 2,300 square miles.') },
  'ottawa-county': { slug: 'ottawa-county', countyName: 'Ottawa County', countySeat: 'Miami', population: 30285, courthouseAddress: '102 E Central Ave, Miami, OK 74354', heroLead: lead('Ottawa County', 'Miami', 'We cover Miami, Commerce, Quapaw, Fairland, and the Kansas and Missouri border tribal jurisdictions of far northeastern Oklahoma.') },
  'pawnee-county': { slug: 'pawnee-county', countyName: 'Pawnee County', countySeat: 'Pawnee', population: 15553, courthouseAddress: '500 Harrison St, Pawnee, OK 74058', heroLead: lead('Pawnee County', 'Pawnee', 'We cover Pawnee, Cleveland, Hallett, Jennings, and the Pawnee Nation tribal jurisdiction of north-central Oklahoma.') },
  'payne-county': { slug: 'payne-county', countyName: 'Payne County', countySeat: 'Stillwater', population: 81646, courthouseAddress: '606 S Husband St, Stillwater, OK 74074', heroLead: lead('Payne County', 'Stillwater', 'We cover Stillwater, Cushing, Perkins, Glencoe, and Oklahoma State University\u2014a major university town with high rental turnover.') },
  'pittsburg-county': { slug: 'pittsburg-county', countyName: 'Pittsburg County', countySeat: 'McAlester', population: 43773, courthouseAddress: '115 E Carl Albert Pkwy, McAlester, OK 74501', heroLead: lead('Pittsburg County', 'McAlester', 'We cover McAlester, Krebs, Hartshorne, Kiowa, and the US-69 corridor through southeastern Oklahoma.') },
  'pontotoc-county': { slug: 'pontotoc-county', countyName: 'Pontotoc County', countySeat: 'Ada', population: 38065, courthouseAddress: '100 W 13th St, Ada, OK 74820', heroLead: lead('Pontotoc County', 'Ada', 'We cover Ada, Byng, Francis, Roff, and the Chickasaw Nation tribal jurisdiction and East Central University area.') },
  'pottawatomie-county': { slug: 'pottawatomie-county', countyName: 'Pottawatomie County', countySeat: 'Shawnee', population: 72454, courthouseAddress: '325 N Broadway Ave, Shawnee, OK 74801', heroLead: lead('Pottawatomie County', 'Shawnee', 'We cover Shawnee, Tecumseh, Dale, McLoud, and the I-40 corridor east of Oklahoma City with strong tribal presence.') },
  'pushmataha-county': { slug: 'pushmataha-county', countyName: 'Pushmataha County', countySeat: 'Antlers', population: 10812, courthouseAddress: '203 SW 3rd St, Antlers, OK 74523', heroLead: lead('Pushmataha County', 'Antlers', 'We cover Antlers, Clayton, Rattan, Tuskahoma, and the Kiamichi Mountains and Choctaw Nation jurisdiction of southeastern Oklahoma.') },
  'roger-mills-county': { slug: 'roger-mills-county', countyName: 'Roger Mills County', countySeat: 'Cheyenne', population: 3442, courthouseAddress: '500 Broadway St, Cheyenne, OK 73628', heroLead: lead('Roger Mills County', 'Cheyenne', 'We cover Cheyenne, Reydon, Hammon, and the Washita Battlefield National Historic Site and Antelope Hills region of western Oklahoma.') },
  'rogers-county': { slug: 'rogers-county', countyName: 'Rogers County', countySeat: 'Claremore', population: 96061, courthouseAddress: '200 S Lynn Riggs Blvd, Claremore, OK 74017', heroLead: lead('Rogers County', 'Claremore', 'We cover Claremore, Catoosa, Verdigris, Oologah, Inola, Foyil, Chelsea, and the northern Tulsa metro corridor along Route 66.') },
  'seminole-county': { slug: 'seminole-county', countyName: 'Seminole County', countySeat: 'Wewoka', population: 23556, courthouseAddress: '110 S Wewoka Ave, Wewoka, OK 74884', heroLead: lead('Seminole County', 'Wewoka', 'We cover Wewoka, Seminole, Konawa, Sasakwa, and the Seminole Nation of Oklahoma tribal headquarters region.') },
  'sequoyah-county': { slug: 'sequoyah-county', countyName: 'Sequoyah County', countySeat: 'Sallisaw', population: 39281, courthouseAddress: '120 E Chickasaw Ave, Sallisaw, OK 74955', heroLead: lead('Sequoyah County', 'Sallisaw', 'We cover Sallisaw, Muldrow, Vian, Roland, and the Arkansas border and I-40 corridor of eastern Oklahoma.') },
  'stephens-county': { slug: 'stephens-county', countyName: 'Stephens County', countySeat: 'Duncan', population: 42848, courthouseAddress: '101 S 11th St, Duncan, OK 73533', heroLead: lead('Stephens County', 'Duncan', 'We cover Duncan, Marlow, Comanche, Velma, and the Halliburton and energy-industry corridor of south-central Oklahoma.') },
  'texas-county': { slug: 'texas-county', countyName: 'Texas County', countySeat: 'Guymon', population: 21384, courthouseAddress: '319 N Main St, Guymon, OK 73942', heroLead: lead('Texas County', 'Guymon', 'We cover Guymon, Hooker, Tyrone, Texhoma, and the central Oklahoma Panhandle meat-processing and agricultural corridor.') },
  'tillman-county': { slug: 'tillman-county', countyName: 'Tillman County', countySeat: 'Frederick', population: 7055, courthouseAddress: '201 N Main St, Frederick, OK 73542', heroLead: lead('Tillman County', 'Frederick', 'We cover Frederick, Tipton, Grandfield, Davidson, and the Red River border ranchland of far southwestern Oklahoma.') },
  'tulsa-county': { slug: 'tulsa-county', countyName: 'Tulsa County', countySeat: 'Tulsa', population: 669279, courthouseAddress: '500 S Denver Ave, Tulsa, OK 74103', heroLead: lead('Tulsa County', 'Tulsa', 'We cover Tulsa, Broken Arrow, Owasso, Bixby, Jenks, Sand Springs, Glenpool, Collinsville, and the entire Tulsa metropolitan region.') },
  'wagoner-county': { slug: 'wagoner-county', countyName: 'Wagoner County', countySeat: 'Wagoner', population: 80981, courthouseAddress: '307 E Cherokee St, Wagoner, OK 74467', heroLead: lead('Wagoner County', 'Wagoner', 'We cover Wagoner, Coweta, Porter, Okay, plus Fort Gibson Lake shoreline properties and the eastern Tulsa metro commuter corridor.') },
  'washington-county': { slug: 'washington-county', countyName: 'Washington County', countySeat: 'Bartlesville', population: 52455, courthouseAddress: '400 S Johnstone Ave, Bartlesville, OK 74003', heroLead: lead('Washington County', 'Bartlesville', 'We cover Bartlesville, Dewey, Copan, Ramona, Ochelata, and the ConocoPhillips corporate and Kansas border region.') },
  'washita-county': { slug: 'washita-county', countyName: 'Washita County', countySeat: 'Cordell', population: 11025, courthouseAddress: '111 E Main St, Cordell, OK 73632', heroLead: lead('Washita County', 'Cordell', 'We cover Cordell, Sentinel, Burns Flat, New Cordell, and the I-40 corridor of western Oklahoma.') },
  'woods-county': { slug: 'woods-county', countyName: 'Woods County', countySeat: 'Alva', population: 8624, courthouseAddress: '407 Government St, Alva, OK 73717', heroLead: lead('Woods County', 'Alva', 'We cover Alva, Waynoka, Freedom, Avard, and Northwestern Oklahoma State University in far northwestern Oklahoma.') },
  'woodward-county': { slug: 'woodward-county', countyName: 'Woodward County', countySeat: 'Woodward', population: 20470, courthouseAddress: '1600 Main St, Woodward, OK 73801', heroLead: lead('Woodward County', 'Woodward', 'We cover Woodward, Mooreland, Sharon, and the ranchland and energy corridor of northwestern Oklahoma.') },
};

export function getCountyData(slug: string): CountyDatum | undefined {
  return COUNTIES[slug];
}

export function getCountySlugsList(): string[] {
  return Object.keys(COUNTIES);
}
