/**
 * Per-county data for Oklahoma county landing pages.
 *
 * Source notes:
 * - Populations pulled from existing static county pages (2024 estimates).
 * - Courthouse addresses verified against county .gov / okcounties.org where
 *   a bug was discovered in the static files (see CORRECTIONS below).
 * - heroLead is a 2-3 sentence production lead written for every county.
 *   Phase 2 will replace per-county heroLeads with swarm-verified unique
 *   prose; the current leads are deliberately formulaic but county-specific
 *   (seat + county name + no pricing, no em-dashes).
 *
 * KNOWN CORRECTIONS applied (bugs that existed in static files):
 * - Love County: was "301 N Broadway St, Walters" (Cotton County's seat).
 *                Corrected to 405 W Main St, Marietta, OK 73448.
 * - Kay County:  was "300 Courthouse Dr, Perry" (Noble County's seat).
 *                Corrected to 201 S Main St, Newkirk, OK 74647.
 * - Kiowa County: was "315 SW 5th St, Lawton" (Comanche County's seat).
 *                 Corrected to 316 S Main St, Hobart, OK 73651.
 * - McIntosh County: was "222 E Dewey Ave, Sapulpa" (Creek County's seat).
 *                    Corrected to 110 N 1st St, Eufaula, OK 74432.
 *
 * VERIFY markers flag addresses that were written as "Courthouse, <city>"
 * in the source files (no street) and still need a verified street address
 * from the swarm.
 */

export interface CountyDatum {
  slug: string;
  countyName: string;
  countySeat: string;
  population?: number;
  courthouseAddress?: string;
  heroLead: string;
}

const lead = (countyName: string, seat: string, extra?: string): string => {
  const base = `Licensed and bonded process server covering ${countyName}, Oklahoma, from the ${seat} county seat to every town and rural route in the county. We deliver summons, subpoenas, evictions, and civil documents with GPS-verified attempts and notarized affidavits ready for filing.`;
  const tail = ` Standard, rush, and same-day service tiers are available; see current rates on our pricing page or call (539) 367-6832 to schedule.`;
  return extra ? `${base} ${extra}${tail}` : `${base}${tail}`;
};

export const COUNTIES: Record<string, CountyDatum> = {
  'adair-county': { slug: 'adair-county', countyName: 'Adair County', countySeat: 'Stilwell', population: 19575, courthouseAddress: '220 W. Division St., Stilwell, OK 74960', heroLead: 'Adair County, nestled in the Ozark Plateau foothills of northeastern Oklahoma, is home to the Strawberry Capital of the World and the heart of the Cherokee Nation, where historic Flint and Going Snake Districts blend rich Native American heritage with agricultural and manufacturing economies. Whether serving process in Stilwell, Westville, or on tribal trust land throughout the county, Just Legal Solutions delivers experienced, knowledgeable service across Oklahoma\'s most uniquely jurisdictional county. Call (539) 367-6832 or visit /contact to get started.' },
  'alfalfa-county': { slug: 'alfalfa-county', countyName: 'Alfalfa County', countySeat: 'Cherokee', population: 5696, courthouseAddress: '300 S. Grand Ave, Suite 8, Cherokee, OK 73728', heroLead: 'Nestled in north-central Oklahoma, Alfalfa County is a rural agricultural powerhouse and the second-largest producer of winter wheat in the state. From the crystal-digging salt flats near Jet to the historic Sod House Museum near Aline, the county offers a unique blend of natural wonders and frontier heritage. Whether you need process serving in Cherokee, Helena, or any of the county\'s ten communities, Just Legal Solutions delivers reliable legal support throughout Alfalfa County. Contact us at (539) 367-6832 or visit our website to get started.' },
  'atoka-county': { slug: 'atoka-county', countyName: 'Atoka County', countySeat: 'Atoka', population: 14600, courthouseAddress: '200 E. Court St., Atoka, OK 74525', heroLead: 'Nestled in the Ouachita Mountains of southeastern Oklahoma, Atoka County blends rich Choctaw heritage with outdoor recreation across 990 square miles of forests, lakes, and rolling hills. Home to the historic Butterfield Overland Mail route, the only Confederate cemetery in Oklahoma, and country music legend Reba McEntire\'s hometown of Chockie, Atoka County offers a unique slice of frontier history. From serving legal papers at the 200 E. Court Street courthouse to navigating the rural roads of Choctaw Country, trust Just Legal Solutions at (539) 367-6832 or visit /contact for reliable process serving throughout Atoka County.' },
  'beaver-county': { slug: 'beaver-county', countyName: 'Beaver County', countySeat: 'Beaver', population: 5025, courthouseAddress: '111 Second St, Beaver, OK 73932', heroLead: 'Beaver County sits in the eastern Oklahoma Panhandle, a vast rural landscape of 1,818 square miles that was once known as No Man\'s Land. Today the county thrives on agriculture, with cattle ranching and wheat farming as its economic backbone, while the town of Beaver proudly hosts the annual World Championship Cow Chip Throwing Contest. For reliable process serving across this expansive county, call (539) 367-6832 or visit our contact page.' },
  'beckham-county': { slug: 'beckham-county', countyName: 'Beckham County', countySeat: 'Sayre', population: 22186, courthouseAddress: '104 S 3rd St, Sayre, OK 73662', heroLead: 'Located in southwestern Oklahoma along the Texas border and historic Route 66, Beckham County blends rich Western heritage with a diversified economy anchored by healthcare, energy, and agriculture. Its stunning domed courthouse in Sayre, featured in The Grapes of Wrath, serves as the legal heart of a county where the Cheyenne and Arapaho Tribes share jurisdictional authority. For reliable process serving throughout Beckham County, call (539) 367-6832 or visit our Contact page.' },
  'blaine-county': { slug: 'blaine-county', countyName: 'Blaine County', countySeat: 'Watonga', population: 8573, courthouseAddress: '212 N. Weigle Ave, Watonga, OK 73772', heroLead: 'Located in west-central Oklahoma, Blaine County encompasses 939 square miles of rolling plains and Gypsum Hills, where agriculture, tribal gaming, and gypsum mining drive the local economy. From the historic 1906 Watonga courthouse to the Cheyenne and Arapaho tribal lands, process serving here requires knowledge of both state and tribal jurisdictions. For reliable service throughout Blaine County, call Just Legal Solutions at (539) 367-6832 or visit us at /contact.' },
  'bryan-county': { slug: 'bryan-county', countyName: 'Bryan County', countySeat: 'Durant', population: 50305, courthouseAddress: '402 W. Evergreen St, Durant, OK 74701', heroLead: 'Located in southeastern Oklahoma\'s Choctaw Country, Bryan County is home to Durant, the \'Magnolia Capital of Oklahoma,\' and serves as the headquarters for the Choctaw Nation of Oklahoma. With Lake Texoma drawing 6 million visitors annually and a growing population of over 50,000, the county combines rich Native American heritage with thriving tourism, manufacturing, and education sectors. For professional process serving throughout Bryan County, contact Just Legal Solutions at (539) 367-6832 or visit us at /contact.' },
  'caddo-county': { slug: 'caddo-county', countyName: 'Caddo County', countySeat: 'Anadarko', population: 26337, courthouseAddress: '201 West Oklahoma Avenue, Anadarko, OK 73005', heroLead: 'Caddo County, Oklahoma, is a region steeped in Native American heritage and agricultural tradition, home to the annual American Indian Exposition in Anadarko and the historic Riverside Indian School, the oldest federally operated Native American boarding school in the United States. From the rolling Gypsum Hills to the shores of Fort Cobb Lake, Caddo County blends rich cultural history with modern economic development. For reliable process serving throughout Caddo County, contact Just Legal Solutions at (539) 367-6832 or visit our /contact page.' },
  'canadian-county': { slug: 'canadian-county', countyName: 'Canadian County', countySeat: 'El Reno', population: 175829, courthouseAddress: '301 N. Choctaw Avenue, El Reno, OK 73036', heroLead: 'Canadian County, Oklahoma\'s fastest-growing county, blends rich frontier heritage—from the Chisholm Trail and Fort Reno to the famous El Reno onion burger—with booming suburban expansion along the Oklahoma City metro. Whether serving legal documents in Yukon, Mustang, El Reno, or surrounding communities, Just Legal Solutions provides reliable process serving throughout the 26th Judicial District. Contact us today at (539) 367-6832 or visit our /contact page.' },
  'carter-county': { slug: 'carter-county', countyName: 'Carter County', countySeat: 'Ardmore', population: 49135, courthouseAddress: '20 "B" St SW, Ardmore, OK 73401', heroLead: 'Carter County sits at the crossroads of south-central Oklahoma, where the historic Healdton Oil Field made it the state\'s top oil-producing county and the vibrant city of Ardmore serves as a regional hub for a 13-county area. With Lake Murray State Park drawing visitors from across the region and the Chickasaw Nation maintaining a strong cultural and economic presence, Carter County blends rich energy heritage with modern healthcare, manufacturing, and tribal enterprise. For professional process serving throughout Carter County, contact Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'cherokee-county': { slug: 'cherokee-county', countyName: 'Cherokee County', countySeat: 'Tahlequah', population: 48700, courthouseAddress: '213 W. Delaware St., Tahlequah, OK 74464', heroLead: 'Nestled in the Ozark foothills of northeastern Oklahoma, Cherokee County blends rich Cherokee Nation heritage with world-class outdoor recreation at Lake Tenkiller and the Illinois River. As home to the Cherokee Nation capital in Tahlequah and Northeastern State University, the county\'s economy is anchored by tribal government, education, and tourism. Contact Just Legal Solutions at (539) 367-6832 or visit /contact for experienced process serving throughout Cherokee County.' },
  'choctaw-county': { slug: 'choctaw-county', countyName: 'Choctaw County', countySeat: 'Hugo', population: 14174, courthouseAddress: '300 E. Duke, Hugo, OK 74743', heroLead: 'Choctaw County sits in the southeastern corner of Oklahoma along the Texas border, encompassing 800 square miles of rolling hills, timberlands, and river valleys drained by the Kiamichi River. From its circus heritage in Hugo to the historic Fort Towson where the last Confederate general surrendered, the county blends unique cultural traditions with deep Choctaw tribal history. When you need reliable process service anywhere in Choctaw County, call Just Legal Solutions at (539) 367-6832 or visit our /contact page.' },
  'cimarron-county': { slug: 'cimarron-county', countyName: 'Cimarron County', countySeat: 'Boise City', population: 2133, courthouseAddress: '1 Courthouse Square, Boise City, OK 73933', heroLead: 'Cimarron County, Oklahoma\'s westernmost county in the Oklahoma Panhandle, holds the unique distinction of being the only U.S. county to border four other states. From the 4,973-foot summit of Black Mesa (Oklahoma\'s highest point) to the historic Santa Fe Trail crossings, this frontier county of 2,133 residents spans 1,841 square miles of ranchlands and wheat fields anchored by the resilient community of Boise City. Call (539) 367-6832 or visit /contact for professional process serving throughout Cimarron County.' },
  'cleveland-county': { slug: 'cleveland-county', countyName: 'Cleveland County', countySeat: 'Norman', population: 300047, courthouseAddress: '201 S Jones Ave, Norman, OK 73069', heroLead: 'Cleveland County, Oklahoma\'s third-most populous county, blends world-class higher education at the University of Oklahoma with a rapidly growing economy spanning healthcare, manufacturing, and research sectors. From its 1889 Land Run origins to its current status as an Oklahoma City metropolitan hub encompassing Norman and Moore, the county offers diverse communities and steady growth. For professional process serving throughout Cleveland County, contact Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'coal-county': { slug: 'coal-county', countyName: 'Coal County', countySeat: 'Coalgate', population: 5414, courthouseAddress: '4 N. Main St, Coalgate, OK 74538', heroLead: 'Coal County, nestled in southeastern Oklahoma\'s Choctaw Country, carries a rich heritage shaped by coal mining since the 1870s and a resilient agricultural economy. From the historic courthouse in Coalgate to the Amish communities of Clarita-Bromide, the county blends industrial history with rural charm. Whether you need legal documents served at the courthouse, a business in Coalgate, or a rural residence in Lehigh, Just Legal Solutions has you covered. Call (539) 367-6832 or visit /contact to get started.' },
  'comanche-county': { slug: 'comanche-county', countyName: 'Comanche County', countySeat: 'Lawton', population: 121396, courthouseAddress: '315 SW 5th Street, Lawton, OK 73501', heroLead: 'Comanche County, anchored by Lawton and Fort Sill in southwestern Oklahoma, blends Great Plains prairie with the rugged granite peaks of the Wichita Mountains. Home to one of America\'s oldest wildlife refuges and named for the Comanche tribal nation whose headquarters remains here today, the county\'s economy thrives on military, healthcare, manufacturing, and tribal enterprise. When you need professional process serving in Comanche County, trust Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'cotton-county': { slug: 'cotton-county', countyName: 'Cotton County', countySeat: 'Walters', population: 5503, courthouseAddress: '301 N. Broadway, Walters, OK 73572', heroLead: 'Established in 1912 as Oklahoma\'s last-created county, Cotton County spans 642 square miles of southwestern Oklahoma plains where agriculture, oil production, and small-town communities define the landscape. From the historic courthouse in Walters to the gaming floors of Kiowa Casino in Devol, the county presents unique process serving challenges across its rural terrain. For reliable legal document delivery throughout Cotton County, trust the local expertise of Just Legal Solutions at (539) 367-6832 or visit our /contact page.' },
  'craig-county': { slug: 'craig-county', countyName: 'Craig County', countySeat: 'Vinita', population: 14506, courthouseAddress: '210 W. Delaware Ave, Vinita, OK 74301', heroLead: 'Craig County, nestled in northeastern Oklahoma\'s rolling prairies on the western edge of the Ozark Plateau, carries a rich Cherokee heritage dating back to the Trail of Tears and was named for Granville Craig, a respected mixed-blood Cherokee farmer. From the historic railroad town of Vinita, Oklahoma\'s second-oldest incorporated town, to the ranchlands that still drive the local economy, Craig County blends deep Native American history with modern healthcare, education, and manufacturing employers. For reliable process serving throughout Craig County\'s five incorporated towns and rural communities, call (539) 367-6832 or visit /contact.' },
  'creek-county': { slug: 'creek-county', countyName: 'Creek County', countySeat: 'Sapulpa', population: 73971, courthouseAddress: '222 E. Dewey St., Sapulpa, OK 74066', heroLead: 'Creek County, established at Oklahoma statehood in 1907, blends rich oil boom heritage with modern manufacturing and tribal commerce along Historic Route 66. From the internationally collectible Frankoma Pottery legacy to the bustling glass plants and distribution centers of today, the county offers a unique mix of history and economic vitality. Whether you need process service in Sapulpa, Bristow, or anywhere across Creek County\'s 970 square miles, contact Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'custer-county': { slug: 'custer-county', countyName: 'Custer County', countySeat: 'Arapaho', population: 28266, courthouseAddress: '675 B Street, Arapaho, OK 73620', heroLead: 'Nestled in west-central Oklahoma\'s Gypsum Hills, Custer County blends rich Cheyenne-Arapaho heritage with a thriving modern economy anchored by Southwestern Oklahoma State University, major food processing, and aerospace history at the Stafford Air & Space Museum. Whether your legal needs take you to Weatherford, Clinton, or the county seat of Arapaho, professional process serving ensures your documents reach their destination efficiently. Contact Just Legal Solutions at (539) 367-6832 or visit our /contact page to get started.' },
  'delaware-county': { slug: 'delaware-county', countyName: 'Delaware County', countySeat: 'Jay', population: 41017, courthouseAddress: '327 S 5th St, Jay, OK 74346', heroLead: 'Nestled in the Ozark foothills of northeastern Oklahoma, Delaware County is home to Grand Lake o\' the Cherokees, one of the state\'s premier recreation destinations, and the historic county seat of Jay, where the Delaware County Courthouse anchors a community rich in Cherokee and Delaware tribal heritage. For reliable process serving throughout Delaware County\'s lake communities and towns, contact Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'dewey-county': { slug: 'dewey-county', countyName: 'Dewey County', countySeat: 'Taloga', population: 4484, courthouseAddress: '216 Broadway, Taloga, OK 73667', heroLead: 'Dewey County spans 1,008 square miles of rolling prairie in west-central Oklahoma, where agriculture, oil and gas production, and wind energy drive the local economy. Named for Admiral George Dewey after his 1898 victory at Manila Bay, the county was once part of the Cheyenne-Arapaho Reservation before opening to settlement in 1892. Whether you need process served at the Taloga courthouse, an oilfield office near Seiling, or a ranch along the Canadian River, Just Legal Solutions covers all of Dewey County—call (539) 367-6832 or visit our website to /contact.' },
  'ellis-county': { slug: 'ellis-county', countyName: 'Ellis County', countySeat: 'Arnett', population: 3749, courthouseAddress: '100 S Washington St, Arnett, OK 73832', heroLead: 'Ellis County stretches across 1,232 square miles of northwest Oklahoma prairie, from the wheat fields and ranches surrounding Arnett to the historic broomcorn town of Shattuck and the towering wind turbines of the 25 Mile Creek Wind Farm. Once part of the Cheyenne-Arapaho Reservation, today the county blends agricultural heritage with renewable energy innovation. Call (539) 367-6832 or visit /contact to discuss your Ellis County process serving needs.' },
  'garfield-county': { slug: 'garfield-county', countyName: 'Garfield County', countySeat: 'Enid', population: 62007, courthouseAddress: '114 W. Broadway Ave, Enid, OK 73701', heroLead: 'Located in north-central Oklahoma, Garfield County is the Wheat Capital of Oklahoma with Enid as its county seat, home to the largest grain storage capacity in the United States, Vance Air Force Base, and a thriving agricultural and food processing economy. Just Legal Solutions provides professional process serving throughout Garfield County — call (539) 367-6832 or visit our /contact page to get started.' },
  'garvin-county': { slug: 'garvin-county', countyName: 'Garvin County', countySeat: 'Pauls Valley', population: 26149, courthouseAddress: '201 W. Grant Ave, Pauls Valley, OK 73075', heroLead: 'Garvin County lies in the heart of south-central Oklahoma\'s Red Bed Plains and Sandstone Hills, where the Washita River winds through rolling ranchland that once produced enough broomcorn to earn Lindsay the title \'Broomcorn Capital of the World.\' From the historic Santa Fe Depot in Pauls Valley to the oil refineries of Wynnewood, our process servers know every road in this 814-square-mile county. Whether your papers need to reach a defendant in town or at a rural ranch gate, call (539) 367-6832 or visit /contact to get started.' },
  'grady-county': { slug: 'grady-county', countyName: 'Grady County', countySeat: 'Chickasha', population: 58353, courthouseAddress: '326 W Choctaw Ave, Chickasha, OK 73018', heroLead: 'Located in south-central Oklahoma, Grady County blends rural charm with suburban growth as part of the Oklahoma City metropolitan area, anchored by the county seat of Chickasha and home to the University of Science and Arts of Oklahoma. From the rolling Red Bed Plains crossed by the Washita River to the world-famous Festival of Light, Grady County offers a unique mix of agricultural heritage and modern development. Contact us at (539) 367-6832 or visit /contact for process serving assistance.' },
  'grant-county': { slug: 'grant-county', countyName: 'Grant County', countySeat: 'Medford', population: 4123, courthouseAddress: '112 E Guthrie St, Medford, OK 73759', heroLead: 'Grant County, Oklahoma, sits on the state\'s northern border in the heart of wheat country, where agriculture, oil production, and small-town life define the landscape. From the historic courthouse in Medford to the wide-open plains along the Chisholm Trail, our process servers know every road in this 1,004-square-mile county. Call (539) 367-6832 today for dependable service.' },
  'greer-county': { slug: 'greer-county', countyName: 'Greer County', countySeat: 'Mangum', population: 5491, courthouseAddress: '106 E. Jefferson, Mangum, OK 73554', heroLead: 'Nestled in southwestern Oklahoma\'s Gypsum Hills and Red Bed Plains, Greer County carries a unique legacy as the former Greer County, Texas, before a landmark 1896 U.S. Supreme Court decision made it part of Oklahoma Territory. Today, this rural county of 5,491 residents is anchored by Mangum, home to the historic 1906 courthouse, the Mangum Brick Company (oldest continuously operated brick plant west of the Mississippi), and Quartz Mountain State Park — one of Oklahoma\'s original seven state parks built by the Civilian Conservation Corps in 1935. Whether you need legal documents served at the courthouse, the Oklahoma State Reformatory in Granite, or anywhere across this ranching and agricultural community, call Just Legal Solutions at (539) 367-6832.' },
  'harmon-county': { slug: 'harmon-county', countyName: 'Harmon County', countySeat: 'Hollis', population: 2315, courthouseAddress: '114 W. Hollis St., Hollis, OK 73550', heroLead: 'Nestled in the southwest corner of Oklahoma along the Texas border, Harmon County is a rural agricultural community of 2,315 residents known as the \'Irrigation Center of the Southwest.\' Named for Judson Harmon, Governor of Ohio and U.S. Attorney General, the county features Hollis as its county seat and is the birthplace of legendary football coach Darrell K. Royal. For reliable process serving throughout Harmon County, from downtown Hollis to the Texas border, contact Just Legal Solutions at (539) 367-6832 or visit our /contact page.' },
  'harper-county': { slug: 'harper-county', countyName: 'Harper County', countySeat: 'Buffalo', population: 3190, courthouseAddress: '311 SE 1st St., Buffalo, OK 73834', heroLead: 'Harper County spans 1,041 square miles of northwest Oklahoma ranchland, home to Buffalo, Laverne, May, and Rosston. Once part of the historic Cherokee Outlet opened in the 1893 Land Run, the county is named for Oscar Green Harper, a teacher and clerk of the Oklahoma Constitutional Convention. For reliable process serving across Harper County\'s wide-open spaces, call (539) 367-6832 or visit /contact.' },
  'haskell-county': { slug: 'haskell-county', countyName: 'Haskell County', countySeat: 'Stigler', population: 11811, courthouseAddress: '202 East Main Street, Stigler, OK 74462', heroLead: 'Haskell County sits in the Sans Bois Mountains of southeastern Oklahoma, where Lake Eufaula and the Robert S. Kerr Reservoir shape a landscape rooted in Choctaw heritage and coal mining history. Today, ranching, healthcare, and tribal enterprises drive a resilient rural economy. For process serving throughout Haskell County, call (539) 367-6832 or visit /contact.' },
  'hughes-county': { slug: 'hughes-county', countyName: 'Hughes County', countySeat: 'Holdenville', population: 13371, courthouseAddress: '200 N. Broadway, Holdenville, OK 74848', heroLead: 'Hughes County, nestled in Oklahoma\'s south-central Sandstone Hills, blends rich Native American heritage with agricultural tradition and modern industry. From the historic streets of Holdenville, birthplace of oil legend T. Boone Pickens, to the winding Canadian River that divides Choctaw and Muscogee (Creek) tribal jurisdictions, this 815-square-mile county presents unique legal landscapes for process serving. Whether your case involves the Allen Gamble Correctional Center, Tyson Foods operations, or a residence along the shores of Holdenville Lake, Just Legal Solutions navigates Hughes County\'s complex jurisdictional terrain with local expertise. Contact us today at (539) 367-6832 or visit /contact to discuss your process serving needs.' },
  'jackson-county': { slug: 'jackson-county', countyName: 'Jackson County', countySeat: 'Altus', population: 24678, courthouseAddress: '101 N Main St, Altus, OK 73521', heroLead: 'Jackson County, Oklahoma, situated in the southwestern corner of the state, blends rich agricultural heritage with a proud military tradition at Altus Air Force Base, where the 97th Air Mobility Wing trains aircrew on C-17, KC-135, and KC-46 aircraft. From the historic 1910 courthouse on the National Register of Historic Places to the Lugert-Altus Irrigation District supporting 47,000 acres of farmland, the county reflects the enduring spirit of western Oklahoma. For reliable process serving throughout Jackson County\'s 804 square miles, contact Just Legal Solutions at (539) 367-6832 or visit our website.' },
  'jefferson-county': { slug: 'jefferson-county', countyName: 'Jefferson County', countySeat: 'Waurika', population: 5374, courthouseAddress: '220 N. Main St., 3rd Floor, Waurika, OK 73573', heroLead: 'Jefferson County sits in southern Oklahoma along the Red River, where the historic Chisholm Trail once drove millions of Texas longhorns northward. From the circus-founded town of Ringling to the Taovayas Village battlefield on the National Register of Historic Places, this county blends ranching heritage with fascinating history across 774 square miles. For process serving in Jefferson County, call Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'johnston-county': { slug: 'johnston-county', countyName: 'Johnston County', countySeat: 'Tishomingo', population: 10272, courthouseAddress: '403 W. Main, Tishomingo, OK 73460', heroLead: 'Nestled in the heart of south-central Oklahoma, Johnston County is a land of deep Chickasaw heritage, where the historic Tishomingo National Capitol stands as testament to a proud tribal legacy. From the 4-H program that began here in 1909 to the precision manufacturing and mining operations that drive today\'s economy, Johnston County blends rich history with modern industry. Whether you\'re navigating legal matters at the courthouse on 403 W. Main or serving process across the county\'s 658 square miles, Just Legal Solutions has you covered. Call (539) 367-6832 or visit /contact.' },
  'kay-county': { slug: 'kay-county', countyName: 'Kay County', countySeat: 'Newkirk', population: 43700, courthouseAddress: '201 S. Main St., Newkirk, OK 74647', heroLead: 'Kay County, Oklahoma - stretching across 945 square miles of rolling Red Bed Plains in north-central Oklahoma - is the only county in the state to retain its original territorial name \'K County\' from the historic 1893 Cherokee Strip Land Run. Home to three sovereign tribal nations, the legendary Miller Brothers 101 Ranch, and the towering Standing Bear monument honoring the landmark Native American civil rights case, Kay County blends deep frontier heritage with modern agricultural, manufacturing, and energy economies. Whether serving legal process at the historic Newkirk courthouse, the Phillips 66 refinery in Ponca City, or anywhere across this Cherokee Outlet landscape, Just Legal Solutions delivers professional process serving throughout Kay County - reach us at (539) 367-6832 or through our contact page.' },
  'kingfisher-county': { slug: 'kingfisher-county', countyName: 'Kingfisher County', countySeat: 'Kingfisher', population: 15820, courthouseAddress: '101 S Main St, Kingfisher, OK 73750', heroLead: 'Located in central Oklahoma along the historic Chisholm Trail, Kingfisher County blends rich agricultural heritage with modern oil and gas production. From the birthplace of Walmart founder Sam Walton to the vibrant communities of Kingfisher and Hennessey, process serving throughout the county requires knowledge of both state and Cheyenne and Arapaho tribal jurisdictions. Contact us at (539) 367-6832 or visit /contact for professional process serving assistance.' },
  'kiowa-county': { slug: 'kiowa-county', countyName: 'Kiowa County', countySeat: 'Hobart', population: 8257, courthouseAddress: '316 S. Main, Hobart, OK 73651', heroLead: 'Kiowa County, nestled in southwestern Oklahoma, encompasses 1,031 square miles of prairie and plains named for the Kiowa people. From the historic Rainy Mountain to the wheat fields that define its economy, the county\'s rich Native American heritage and agricultural roots create a unique landscape for process serving. Contact Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'latimer-county': { slug: 'latimer-county', countyName: 'Latimer County', countySeat: 'Wilburton', population: 9509, courthouseAddress: '109 N Central, Room 200, Wilburton, OK 74578', heroLead: 'Nestled in the scenic Sans Bois Mountains of southeastern Oklahoma, Latimer County encompasses 729 square miles of hilly, forested terrain that was once a legendary hideout for Old West outlaws and is now home to Robbers Cave State Park, Eastern Oklahoma State College, and the historic coal town of Wilburton. Whether you need process served at the Latimer County Courthouse, a rural homestead outside Red Oak, or anywhere across this Choctaw Nation reservation county, contact Just Legal Solutions at (539) 367-6832 or visit our /contact page.' },
  'leflore-county': { slug: 'leflore-county', countyName: 'LeFlore County', countySeat: 'Poteau', population: 49854, courthouseAddress: '100 S. Broadway, Poteau, OK 74953', heroLead: 'LeFlore County sits in southeastern Oklahoma where the Ouachita Mountains meet the Arkansas River, encompassing 1,609 square miles of scenic terrain including the Talimena Scenic Byway and Cavanal Hill, the \'World\'s Highest Hill.\' The county honors the LeFlore family of the Choctaw Nation and serves as a hub for outdoor recreation, poultry processing, and education anchored by Carl Albert State College in Poteau. For professional process serving throughout LeFlore County, contact Just Legal Solutions at (539) 367-6832 or visit our website to /contact.' },
  'lincoln-county': { slug: 'lincoln-county', countyName: 'Lincoln County', countySeat: 'Chandler', population: 34972, courthouseAddress: '811 Manvel Ave, Chandler, OK 74834', heroLead: 'Named by popular vote in 1891 to honor President Abraham Lincoln, Lincoln County sits at the geographic heart of Oklahoma and was once the top cotton-producing county in the state. Today, this east-central Oklahoma county blends its agricultural heritage with oil and gas production, Sac and Fox Nation tribal enterprises, and Route 66 tourism along the historic Mother Road. Whether you need process served at the Lincoln County Courthouse in Chandler, the Sac and Fox tribal court in Stroud, or anywhere across the county\'s 966 square miles, Just Legal Solutions delivers prompt, professional service throughout Lincoln County — call (539) 367-6832 or visit /contact.' },
  'logan-county': { slug: 'logan-county', countyName: 'Logan County', countySeat: 'Guthrie', population: 53860, courthouseAddress: '301 E Harrison Ave, Guthrie, OK 73044', heroLead: 'Logan County, located in north-central Oklahoma just 30 miles north of Oklahoma City, blends rich territorial history with modern suburban growth. From its Victorian-era county seat of Guthrie, Oklahoma\'s first capital, to the rolling Red Bed Plains and Cimarron River valley, the county offers a unique mix of historic preservation and economic development. Whether serving legal documents at the 1907 courthouse or along the interstate corridor, trust Just Legal Solutions for reliable process serving throughout Logan County, call (539) 367-6832 or visit our contact page.' },
  'love-county': { slug: 'love-county', countyName: 'Love County', countySeat: 'Marietta', population: 10423, courthouseAddress: '405 W. Main, Marietta, OK 73448', heroLead: 'Nestled along Oklahoma\'s southern border with Texas, Love County combines rich Chickasaw heritage with modern economic growth driven by WinStar World Casino and a revitalized Dollar Tree distribution hub. Named for Overton Love, a prominent Chickasaw judge and entrepreneur who settled here in 1843, the county seat of Marietta anchors a community of rolling Red River Plains terrain, lakeside recreation at Lake Murray and Lake Texoma, and strategic Interstate 35 commerce. For reliable process serving throughout Love County, call Just Legal Solutions at (539) 367-6832 or visit us online at /contact.' },
  'major-county': { slug: 'major-county', countyName: 'Major County', countySeat: 'Fairview', population: 7569, courthouseAddress: '500 E. Broadway, Fairview, OK 73737', heroLead: 'Nestled in northwestern Oklahoma, Major County blends rich agricultural heritage with remarkable geological wonders, from the shimmering Glass Mountains to the ancient Ames Astrobleme meteorite crater that has produced millions of barrels of oil. The county seat of Fairview serves as a hub for the region\'s wheat farming, cattle ranching, and gypsum manufacturing industries. Whether you\'re serving legal documents at the courthouse on 500 E. Broadway or at one of the county\'s major employers, Just Legal Solutions has the local knowledge to get the job done right—call (539) 367-6832 or visit /contact.' },
  'marshall-county': { slug: 'marshall-county', countyName: 'Marshall County', countySeat: 'Madill', population: 16147, courthouseAddress: '100 Plaza, Madill, OK 73446', heroLead: 'Nestled along the shores of Lake Texoma, Marshall County is Oklahoma\'s smallest county by land area but packs rich history within its 427 square miles. From the historic 1913 courthouse in Madill to the Chickasaw Nation\'s West Bay Casino & Resort in Kingston, the county blends Native American heritage, lakeside recreation, and manufacturing strength. Whether you need process service at a lakeside property or in downtown Madill, Just Legal Solutions delivers county-wide coverage—call (539) 367-6832 or visit /contact.' },
  'mayes-county': { slug: 'mayes-county', countyName: 'Mayes County', countySeat: 'Pryor Creek', population: 40144, courthouseAddress: 'One Court Place, Pryor, OK 74361', heroLead: 'Nestled in the lake country of northeastern Oklahoma, Mayes County blends rich Cherokee heritage with modern industry, from the historic Pensacola Dam creating Grand Lake o\' the Cherokees to Google\'s second-largest global data center at MidAmerica Industrial Park. Whether navigating civil process near the county seat of Pryor Creek or serving papers near the shores of Lake Hudson, local expertise matters. Call (539) 367-6832 or visit /contact to get started.' },
  'mcclain-county': { slug: 'mcclain-county', countyName: 'McClain County', countySeat: 'Purcell', population: 48434, courthouseAddress: '121 N. 2nd Street, Suite 231, Purcell, OK 73080', heroLead: 'Located in the heart of south-central Oklahoma, McClain County is one of the fastest-growing counties in the Oklahoma City metro area, encompassing 580 square miles and home to over 48,000 residents across vibrant communities like Newcastle, Purcell, and Blanchard. From its historic Chickasaw Nation heritage to its thriving gaming, education, and healthcare industries, McClain County combines small-town charm with modern economic vitality. Whether you need process serving at the Purcell courthouse, a business in Newcastle, or a residence in Goldsby, Just Legal Solutions delivers reliable, efficient service throughout McClain County. Contact us today at (539) 367-6832 or visit our /contact page to get started.' },
  'mccurtain-county': { slug: 'mccurtain-county', countyName: 'McCurtain County', countySeat: 'Idabel', population: 30805, courthouseAddress: '108 N. Central Ave, Idabel, OK 74745', heroLead: 'McCurtain County, Oklahoma\'s third-largest county at 1,902 square miles, sits in the southeastern corner of the state where the Ouachita Mountains meet the Red River Valley. From the towering pines around Broken Bow Lake to the timber mills of Idabel and Valliant, the county\'s economy blends tourism, forestry, and manufacturing into a unique southeastern Oklahoma character. Whether you need legal documents served in Idabel, Broken Bow, or any rural community in between, Just Legal Solutions provides experienced process serving throughout McCurtain County. Call (539) 367-6832 or visit /contact.' },
  'mcintosh-county': { slug: 'mcintosh-county', countyName: 'McIntosh County', countySeat: 'Eufaula', population: 19710, courthouseAddress: '110 N 1st St, Eufaula, OK 74432', heroLead: 'Named for an influential Muscogee Creek family, McIntosh County is home to Lake Eufaula, Oklahoma\'s largest reservoir, and the historic Honey Springs Battlefield. The county blends rich Native American heritage with agriculture, tourism and Lake Eufaula\'s recreational economy. For professional process serving throughout McIntosh County, contact us at (539) 367-6832 or visit /contact.' },
  'murray-county': { slug: 'murray-county', countyName: 'Murray County', countySeat: 'Sulphur', population: 13754, courthouseAddress: '1001 W. Wyandotte Ave, Sulphur, OK 73086', heroLead: 'Nestled in the Arbuckle Mountains of south-central Oklahoma, Murray County is a 425-square-mile gem named for \'Alfalfa Bill\' Murray, featuring the mineral springs of Sulphur, the cascading waters of Turner Falls, and the Chickasaw National Recreation Area. With a population of approximately 13,754 residents, the county\'s economy thrives on tourism, Chickasaw Nation enterprises, education, and healthcare anchored by Arbuckle Memorial Hospital. Whether you need legal documents served at the courthouse in Sulphur, at a resort property, or anywhere across this historic Chickasaw Nation territory, our experienced team ensures timely and compliant delivery throughout Murray County. Contact us at (539) 367-6832 or visit /contact to get started.' },
  'muskogee-county': { slug: 'muskogee-county', countyName: 'Muskogee County', countySeat: 'Muskogee', population: 66752, courthouseAddress: '220 State Street, Muskogee, OK 74401', heroLead: 'Muskogee County sits at the confluence of the Arkansas, Verdigris, and Grand Rivers in eastern Oklahoma, where the historic Muscogee (Creek) Nation\'s reservation boundaries were reaffirmed by the landmark McGirt decision. From the manufacturing corridor anchored by Georgia-Pacific and Dal-Tile to the healthcare hub at Saint Francis Hospital, our process servers navigate the county\'s diverse landscape daily to deliver reliable legal service. Contact Just Legal Solutions at (539) 367-6832 or visit our website to schedule service anywhere in Muskogee County.' },
  'noble-county': { slug: 'noble-county', countyName: 'Noble County', countySeat: 'Perry', population: 10896, courthouseAddress: '300 Courthouse Drive, Perry, OK 73077', heroLead: 'Noble County, located in north-central Oklahoma, is a rural agricultural community known as the home of Ditch Witch, the world\'s leading manufacturer of underground construction equipment. From the rolling prairie wheat fields surrounding Perry to the historic Cherokee Outlet lands, the county blends manufacturing innovation with agricultural heritage. For reliable process serving throughout Noble County, call Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'nowata-county': { slug: 'nowata-county', countyName: 'Nowata County', countySeat: 'Nowata', population: 9561, courthouseAddress: '229 N. Maple St., Nowata, OK 74048', heroLead: 'Nestled along the Kansas border in northeastern Oklahoma, Nowata County carries a Delaware Indian name meaning welcome and was once home to the worlds largest shallow oil field. Today the countys economy blends agriculture, manufacturing, and Cherokee Nation enterprises across its six small towns. For reliable process serving throughout Nowata County, call Just Legal Solutions at (539) 367-6832 or visit our /contact page.' },
  'okfuskee-county': { slug: 'okfuskee-county', countyName: 'Okfuskee County', countySeat: 'Okemah', population: 11364, courthouseAddress: '209 N. 3rd Street, Okemah, OK 74859', heroLead: 'Nestled in the Sandstone Hills of east-central Oklahoma, Okfuskee County is a land of rich Creek heritage, home to the legendary Woody Guthrie\'s birthplace of Okemah, and one of America\'s last historically all-Black towns in Boley. From its oil boom past to its modern agricultural and tribal economy, the county reflects the diverse tapestry of Oklahoma history. For reliable process serving throughout Okfuskee County and its reservation lands, contact Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'oklahoma-county': { slug: 'oklahoma-county', countyName: 'Oklahoma County', countySeat: 'Oklahoma City', population: 816490, courthouseAddress: '321 Park Avenue, Oklahoma City, OK 73102', heroLead: 'Oklahoma County, home to the state capital Oklahoma City and over 816,000 residents, serves as the economic and political heart of Oklahoma. Founded during the 1889 Land Run, the county spans 718 square miles and hosts major employers including Tinker Air Force Base, the State of Oklahoma, and INTEGRIS Health. For process serving throughout Oklahoma County, contact (539) 367-6832 or visit /contact.' },
  'okmulgee-county': { slug: 'okmulgee-county', countyName: 'Okmulgee County', countySeat: 'Okmulgee', population: 37084, courthouseAddress: '314 W 7th St, Okmulgee, OK 74447', heroLead: 'Nestled in east-central Oklahoma within the Muscogee (Creek) Nation Reservation, Okmulgee County blends rich Native American heritage with a thriving manufacturing base and world-class fishing at Dripping Springs Lake. From the historic Creek Council House in downtown Okmulgee to the nine global-exporting manufacturers driving the local economy, our process servers cover all 702 square miles of this diverse county. Call (539) 367-6832 or visit /contact to schedule service.' },
  'osage-county': { slug: 'osage-county', countyName: 'Osage County', countySeat: 'Pawhuska', population: 46495, courthouseAddress: '600 Grandview Ave, Pawhuska, OK 74056', heroLead: 'Osage County is Oklahoma\'s largest county at 2,246 square miles, entirely coextensive with the Osage Nation Reservation and rich with Native American heritage, oil history, and the tourism buzz from Ree Drummond\'s Pioneer Woman Mercantile in Pawhuska. For reliable process serving throughout this unique jurisdiction, contact (539) 367-6832 or visit /contact.' },
  'ottawa-county': { slug: 'ottawa-county', countyName: 'Ottawa County', countySeat: 'Miami', population: 30285, courthouseAddress: '102 E. Central Avenue, Miami, OK 74354', heroLead: 'Nestled in Oklahoma\'s northeastern corner where the Sooner State meets Kansas and Missouri, Ottawa County is a land of deep Native American heritage, home to nine federally recognized tribes, and the historic heart of the Tri-State Lead and Zinc District that once supplied the world. From the vibrant county seat of Miami to the rolling hills of the Ozark Plateau, the county blends tribal sovereignty with frontier history. Whether you need legal documents served at the courthouse, a casino, or anywhere across this unique county, trust Just Legal Solutions at (539) 367-6832.' },
  'pawnee-county': { slug: 'pawnee-county', countyName: 'Pawnee County', countySeat: 'Pawnee', population: 16111, courthouseAddress: '500 Harrison, Pawnee, OK 74058', heroLead: 'Pawnee County in north-central Oklahoma is a 595-square-mile county steeped in Native American heritage, named for the Pawnee Nation whose tribal headquarters remain in the county seat of Pawnee. From the historic Pawnee Bill Ranch to the Cleveland Area Hospital serving as the county\'s only healthcare facility, Pawnee County blends Western history with rural Oklahoma charm. For reliable process serving throughout Pawnee County, call Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'payne-county': { slug: 'payne-county', countyName: 'Payne County', countySeat: 'Stillwater', population: 84199, courthouseAddress: '606 S. Husband Street, Stillwater, OK 74074', heroLead: 'Home to Oklahoma State University and the Pipeline Crossroads of the World in Cushing, Payne County sits at the heart of north-central Oklahoma, where education, energy, and agriculture converge in a vibrant community of over 84,000 residents. From the historic courthouse in Stillwater to the oil tank farms of Cushing, Just Legal Solutions delivers reliable process serving across every corner of Payne County. Contact us at (539) 367-6832 or visit our website to get started.' },
  'pittsburg-county': { slug: 'pittsburg-county', countyName: 'Pittsburg County', countySeat: 'McAlester', population: 43395, courthouseAddress: '115 E Carl Albert Parkway, McAlester, OK 74501', heroLead: 'Pittsburg County, anchored by McAlester in the heart of the Choctaw Nation reservation, blends rich coal mining heritage with modern defense manufacturing and healthcare industries. Named for Pittsburgh, Pennsylvania at Oklahoma statehood in 1907, the county spans 1,378 square miles from the shores of Lake Eufaula to the Ouachita Mountains. Whether you need process serving at the courthouse, the McAlester Army Ammunition Plant, or anywhere in Pittsburg County, call (539) 367-6832 or visit /contact.' },
  'pontotoc-county': { slug: 'pontotoc-county', countyName: 'Pontotoc County', countySeat: 'Ada', population: 38300, courthouseAddress: '120 West 13th Street, Ada, OK 74820', heroLead: 'Pontotoc County sits in the heart of south-central Oklahoma, anchored by Ada, home to the Chickasaw Nation headquarters and East Central University. From the historic streets of downtown Ada to the rural communities of Allen, Byng, and Stonewall, our process servers navigate Pontotoc County\'s 725 square miles to deliver your legal documents promptly. Contact Just Legal Solutions at (539) 367-6832 or visit /contact to learn how we can assist with your process serving needs throughout the 22nd Judicial District.' },
  'pottawatomie-county': { slug: 'pottawatomie-county', countyName: 'Pottawatomie County', countySeat: 'Shawnee', population: 74446, courthouseAddress: '325 N Broadway Ave, Shawnee, OK 74801', heroLead: 'Pottawatomie County sits at the crossroads of east-central Oklahoma, where the North Canadian River winds through 793 square miles of rolling Sandstone Hills. Home to Shawnee and four federally recognized tribal nations, the county blends rich Native American heritage with modern manufacturing and healthcare economies. Whether you need process served at the courthouse on Broadway, one of the 70-plus manufacturing plants, or anywhere across the county, Just Legal Solutions delivers statewide coverage with local expertise. Call (539) 367-6832 or visit /contact to get started.' },
  'pushmataha-county': { slug: 'pushmataha-county', countyName: 'Pushmataha County', countySeat: 'Antlers', population: 10800, courthouseAddress: '203 SW 3rd Street, Antlers, OK 74523', heroLead: 'Nestled in the rugged Kiamichi Mountains of southeastern Oklahoma, Pushmataha County encompasses 1,423 square miles of scenic Choctaw Country where the historic Choctaw Capitol at Tuskahoma stands as a testament to the region\'s rich Native American heritage. From the timber-rich hills to the Kiamichi River valley communities of Antlers, Clayton, and Rattan, process serving in this rural mountain county requires local knowledge and persistence. Trust the experienced team at Just Legal Solutions to navigate Pushmataha County\'s unique terrain and get your documents served efficiently—call (539) 367-6832 or visit /contact to get started.' },
  'roger-mills-county': { slug: 'roger-mills-county', countyName: 'Roger Mills County', countySeat: 'Cheyenne', population: 3304, courthouseAddress: '500 East Broadway, Cheyenne, OK 73628', heroLead: 'Roger Mills County sits atop the Panhandle-Hugoton Field, one of the largest-volume gas fields in the United States, in the vast prairies of western Oklahoma where agriculture and energy production drive the local economy. From the county seat of Cheyenne to the historic Washita Battlefield, our process servers cover every corner of this 1,146-square-mile county. Contact Just Legal Solutions at (539) 367-6832 or visit /contact for professional process serving in Roger Mills County.' },
  'rogers-county': { slug: 'rogers-county', countyName: 'Rogers County', countySeat: 'Claremore', population: 101371, courthouseAddress: '200 S. Lynn Riggs Blvd, Claremore, OK 74017', heroLead: 'Rogers County, Oklahoma, birthplace of Will Rogers and one of the fastest-growing counties in the state, combines rich Cherokee heritage with a thriving economy driven by manufacturing, healthcare, education, and the Tulsa Port of Catoosa. From the historic courthouse in Claremore to the shores of 29,500-acre Oologah Lake, Rogers County demands process servers who understand both state and Cherokee Nation tribal jurisdiction. Call Just Legal Solutions at (539) 367-6832 or visit /contact.' },
  'seminole-county': { slug: 'seminole-county', countyName: 'Seminole County', countySeat: 'Wewoka', population: 23351, courthouseAddress: '120 S. Wewoka Ave., Wewoka, OK 74884', heroLead: 'Located in east-central Oklahoma between the North Canadian and Canadian Rivers, Seminole County encompasses 640 square miles of historic Seminole Nation territory. From the world-famous Greater Seminole Oil Field that transformed global petroleum production in the 1920s to today\'s diverse economy of manufacturing, education, and agriculture, the county blends deep Native American heritage with modern industry. Let Just Legal Solutions handle your process serving needs throughout Seminole County. Call (539) 367-6832 or visit /contact.' },
  'sequoyah-county': { slug: 'sequoyah-county', countyName: 'Sequoyah County', countySeat: 'Sallisaw', population: 40555, courthouseAddress: '120 E. Chickasaw Ave, Sallisaw, OK 74955', heroLead: 'Sequoyah County sits at Oklahoma\'s eastern edge, where the Ozark Plateau meets the Ouachita Mountains, encompassing 714 square miles of diverse terrain including the crystal-clear waters of Lake Tenkiller and the historic grounds where the Cherokee Nation established its first capital, Tahlonteeskee, in 1829. The county, named for Sequoyah who brought literacy to the Cherokee people through his syllabary, remains deeply connected to Cherokee heritage while its economy thrives on healthcare, manufacturing, education, and tourism serving a population of over 40,000 residents. For professional process serving throughout Sequoyah County and beyond, call (539) 367-6832 or visit /contact.' },
  'stephens-county': { slug: 'stephens-county', countyName: 'Stephens County', countySeat: 'Duncan', population: 44014, courthouseAddress: '101 S 11th St, Suite 301, Duncan, OK 73533', heroLead: 'Located in south-central Oklahoma, Stephens County is a vibrant community anchored by Duncan, the county seat, with deep roots in oil and gas production dating back to 1918. The county spans 891 square miles within the historic Chickasaw Nation and is home to approximately 44,000 residents who enjoy the Chisholm Trail Heritage Center, Lake Humphreys, and a diverse economy led by healthcare, education, and energy sectors. For reliable process serving throughout Stephens County, contact Just Legal Solutions at (539) 367-6832 or visit our /contact page.' },
  'texas-county': { slug: 'texas-county', countyName: 'Texas County', countySeat: 'Guymon', population: 20577, courthouseAddress: '319 N Main St, Guymon, OK 73942', heroLead: 'Texas County anchors the Oklahoma Panhandle with Guymon as its county seat, spanning 2,049 square miles of High Plains agriculture and energy production. From the massive Seaboard Foods pork processing plant to the historic 1927 Texas County Courthouse on Main Street, this county blends industrial scale with frontier heritage. Contact Just Legal Solutions at (539) 367-6832 for experienced process serving across Texas County\'s vast landscape.' },
  'tillman-county': { slug: 'tillman-county', countyName: 'Tillman County', countySeat: 'Frederick', population: 6736, courthouseAddress: '201 N Main St, Frederick, OK 73542', heroLead: 'Nestled in southwestern Oklahoma along the Red River, Tillman County is where cotton and wheat meet across 879 square miles of rolling prairie. From the historic 1921 courthouse in Frederick to the World War II airfield legacy, the county blends agricultural tradition with growing manufacturing. Whether you need process serving in Frederick, Grandfield, or Tipton, Just Legal Solutions covers all of Tillman County efficiently. Call (539) 367-6832 or visit /contact to get started.' },
  'tulsa-county': { slug: 'tulsa-county', countyName: 'Tulsa County', countySeat: 'Tulsa', population: 693514, courthouseAddress: '500 S. Denver Ave, Tulsa, OK 74103', heroLead: 'Tulsa County, Oklahoma\'s second-most populous county with nearly 700,000 residents, spans 587 square miles of northeastern Oklahoma encompassing the city of Tulsa, the \'Oil Capital of the World.\' Founded at statehood in 1907, the county sits within the historic reservation boundaries of both the Cherokee Nation and Muscogee (Creek) Nation, creating a distinctive legal environment shaped by the landmark McGirt v. Oklahoma decision. From the Art Deco skyline of downtown Tulsa to the bustling suburbs of Broken Arrow and Owasso, our licensed process servers navigate this complex jurisdiction daily. Contact Just Legal Solutions at (539) 367-6832 or visit /contact for reliable service throughout Tulsa County.' },
  'wagoner-county': { slug: 'wagoner-county', countyName: 'Wagoner County', countySeat: 'Wagoner', population: 91257, courthouseAddress: '307 E. Cherokee Street, Wagoner, OK 74467', heroLead: 'Nestled in northeastern Oklahoma\'s Ozark Highlands, Wagoner County spans 591 square miles where the Arkansas, Verdigris, and Grand rivers converge, creating the fertile Three Forks region that has drawn settlers since prehistoric times. From the Civil War\'s Battle of Flat Rock to the rail hub founded by Henry \'Bigfoot\' Wagoner, this rapidly growing county blends rich Native American heritage with modern manufacturing and lake recreation centered on 19,900-acre Fort Gibson Lake. For trusted legal document service throughout Wagoner County, call (539) 367-6832 or visit /contact.' },
  'washington-county': { slug: 'washington-county', countyName: 'Washington County', countySeat: 'Bartlesville', population: 54060, courthouseAddress: '420 S. Johnstone Ave., Bartlesville, OK 74003', heroLead: 'Washington County, Oklahoma\'s smallest county by area at just 415 square miles, packs a powerful economic punch as the historic home of Phillips Petroleum and the vibrant Bartlesville metro area with over 54,000 residents. From the iconic Frank Lloyd Wright Price Tower to the world-class Woolaroc Museum, this northeastern Oklahoma county blends oil heritage with cultural treasures on the edge of the Osage Hills. For reliable process serving throughout Washington County, call (539) 367-6832 or visit /contact.' },
  'washita-county': { slug: 'washita-county', countyName: 'Washita County', countySeat: 'New Cordell', population: 10924, courthouseAddress: '111 E Main St, Cordell, OK 73632', heroLead: 'Washita County sits in western Oklahoma where wheat fields, cotton ground, and cattle pasture meet the recreational draw of Foss State Park and the wide Foss Reservoir at its center. The county is anchored by New Cordell, with its distinctive copper-domed courthouse on the town square, and stretches across ten incorporated communities that have long depended on agriculture, oil and gas, and the steady traffic of Interstate 40. Whether your serve is on the courthouse square or at a lakeside cabin, Just Legal Solutions knows the territory and delivers fast, documented service. Call (539) 367-6832 or visit /contact to get started.' },
  'woods-county': { slug: 'woods-county', countyName: 'Woods County', countySeat: 'Alva', population: 8582, courthouseAddress: '407 Government St, Alva, OK 73717', heroLead: 'Woods County sits in the heart of northwest Oklahoma\'s high plains, where agriculture, education, and outdoor recreation define a rural economy anchored by Northwestern Oklahoma State University in Alva. From the gypsum-capped Glass Mountains to the sand dunes of Little Sahara State Park, the county\'s 1,290 square miles blend ranching heritage with natural wonders that draw visitors from across the region. Whether you need service in downtown Alva, at a ranch outside Freedom, or near Alabaster Caverns State Park, Just Legal Solutions covers every corner of Woods County — call (539) 367-6832 or visit /contact to get started.' },
  'woodward-county': { slug: 'woodward-county', countyName: 'Woodward County', countySeat: 'Woodward', population: 19991, courthouseAddress: '1600 Main Street, Suite 4, Woodward, OK 73801', heroLead: 'Located in northwestern Oklahoma\'s Osage Plains, Woodward County spans 1,242 square miles of rolling prairie and gypsum hills, home to 19,991 residents, the world-famous Alabaster Caverns State Park, and historic Fort Supply where George Custer launched the Battle of the Washita. The county seat of Woodward anchors a regional energy hub powered by oil, gas, and wind farms, with service of process throughout the county handled efficiently by Just Legal Solutions at (539) 367-6832 or via /contact.' },
};

export function getCountyData(slug: string): CountyDatum | undefined {
  return COUNTIES[slug];
}

export function getCountySlugsList(): string[] {
  return Object.keys(COUNTIES);
}
