export interface Video {
  videoId: string;
  title: string;
  description: string;
  datePublished: string;
  duration: string; // ISO 8601
  relatedPage?: string;
  category: string;
  isShort: boolean;
}

export function normalizeShortSeo(video: Video): Video {
  if (!video.isShort) return video;

  let title = video.title.trim();
  if (!/\boklahoma\b/i.test(title)) {
    title = `${title} | Oklahoma`;
  }

  let description = video.description.trim();
  if (!/\boklahoma\b/i.test(description)) {
    description = `${description} Oklahoma process serving and notary guidance from Just Legal Solutions.`;
  }

  return {
    ...video,
    title,
    description,
  };
}

export const featuredVideos: Video[] = [
  /* ── Animated Story-Driven Shorts (Noir Illustrations + Voiceover) ── */
  {
    videoId: 'Vgt5i9tDD0M',
    title: 'What Is a Drop Serve? — Oklahoma Process Serving Explained',
    description: 'Animated explainer on what a drop serve is and when Oklahoma process servers can legally use it. Noir-style illustrations with professional voiceover.',
    datePublished: '2026-05-04',
    duration: 'PT50S',
    relatedPage: '/process-serving',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: '9GYj9Bg4Pz8',
    title: 'What Happens If You Dodge a Process Server? — Oklahoma Law',
    description: 'Animated short explaining what really happens when someone tries to avoid being served in Oklahoma — from alternative service to default judgment.',
    datePublished: '2026-05-04',
    duration: 'PT45S',
    relatedPage: '/what-happens-if-someone-refuses-service',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'LAtxl-D9PjY',
    title: 'Can You Be Served at Work? — Oklahoma Process Serving Rules',
    description: 'Animated explainer covering whether process servers can legally serve you at your workplace in Oklahoma, and what the rules are.',
    datePublished: '2026-05-04',
    duration: 'PT45S',
    relatedPage: '/process-serving',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: '-XE-5ZgMhuw',
    title: 'Default Judgment Explained — What Happens When You Ignore a Lawsuit in Oklahoma',
    description: 'Animated story-driven short explaining how default judgments work in Oklahoma when defendants fail to respond after being properly served.',
    datePublished: '2026-05-04',
    duration: 'PT50S',
    relatedPage: '/blog/oklahoma-default-judgment-guide',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'Ht_y4O-CESo',
    title: 'Skip Tracing: How Process Servers Find You — Oklahoma',
    description: 'Animated noir-style short showing how professional process servers use skip tracing to locate hard-to-find defendants in Oklahoma.',
    datePublished: '2026-05-04',
    duration: 'PT50S',
    relatedPage: '/ai-skip-tracing-guide-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: '-rKfHjqATaA',
    title: 'What Is Substitute Service? — Oklahoma Process Serving Explained',
    description: 'Animated story-driven short explaining what substitute service means in Oklahoma and when courts allow alternatives to personal service.',
    datePublished: '2026-05-08',
    duration: 'PT50S',
    relatedPage: '/blog/substitute-service-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'jYrzICW6F5k',
    title: 'Eviction Process in Oklahoma — Step-by-Step Guide',
    description: 'Animated explainer covering the Oklahoma eviction process, from 5-day pay or quit notices to forcible entry and detainer court hearings.',
    datePublished: '2026-05-08',
    duration: 'PT50S',
    relatedPage: '/blog/how-to-serve-eviction-notices-in-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'WT-mNNPlkyg',
    title: 'How to Serve a Business or LLC — Oklahoma Corporate Process Serving',
    description: 'Noir-style animated short showing how to properly serve a business entity, LLC, or corporation with legal papers in Oklahoma.',
    datePublished: '2026-05-08',
    duration: 'PT50S',
    relatedPage: '/blog/serve-business-corporation-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'WBrTTY5KtoE',
    title: 'Protective Orders: How They Get Served in Oklahoma',
    description: 'Animated short explaining how protective and restraining orders are legally and safely served in Oklahoma.',
    datePublished: '2026-05-08',
    duration: 'PT50S',
    relatedPage: '/blog/how-to-file-protective-order-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'U1Hb0QwD5AM',
    title: 'What to Do After You\'ve Been Served — Oklahoma Legal Guide',
    description: 'Animated explainer walking you through exactly what to do next, your rights, and your deadlines after being served legal papers in Oklahoma.',
    datePublished: '2026-05-08',
    duration: 'PT50S',
    relatedPage: '/blog/what-to-do-when-served-papers-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'g4UN3O-9yIE',
    title: 'Service by Publication Explained — Oklahoma Law',
    description: 'Animated short explaining when service by publication is allowed in Oklahoma as a last resort, and what the court requires.',
    datePublished: '2026-05-08',
    duration: 'PT50S',
    relatedPage: '/blog/oklahoma-service-by-publication',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'l8Jgzjrnx-4',
    title: 'Can You Refuse to Be Served? — Legal Reality in Oklahoma',
    description: 'What happens when someone tries to refuse service in Oklahoma? This animated short covers the reality of legal document delivery.',
    datePublished: '2026-05-08',
    duration: 'PT50S',
    relatedPage: '/what-happens-if-someone-refuses-service',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'rDnzN0AedHM',
    title: 'Rush & Emergency Process Serving in Oklahoma',
    description: 'Animated story explaining how rush and same-day process serving works in Oklahoma for urgent legal matters.',
    datePublished: '2026-05-08',
    duration: 'PT50S',
    relatedPage: '/rush-vs-standard-vs-same-day-service',
    category: 'Featured',
    isShort: false,
  },
  /* ── Full-Length Featured Videos ── */
  {
    videoId: 'ApPeLMDA5wU',
    title: 'Oklahoma Eviction Process — Landlord\'s Complete Step-by-Step Guide',
    description: 'The complete landlord\'s guide to the Oklahoma eviction process — every step from notice to court order, explained by a licensed process server.',
    datePublished: '2026-04-01',
    duration: 'PT15M0S',
    relatedPage: '/blog/how-to-serve-eviction-notices-in-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'IEKOF4TiEDY',
    title: 'Attorney\'s Guide to Hiring a Process Server in Oklahoma | Just Legal Solutions',
    description: 'What attorneys need to know when hiring a process server in Oklahoma — licensing, GPS documentation, affidavits, and rush service options.',
    datePublished: '2026-04-01',
    duration: 'PT12M0S',
    relatedPage: '/process-serving',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: '4TeTwsMP3dw',
    title: 'Free Process Server Tools & Resources for Oklahoma Servers',
    description: 'Free tools, apps, and resources every Oklahoma process server should know about in 2026.',
    datePublished: '2026-04-01',
    duration: 'PT10M0S',
    relatedPage: '/process-server-equipment-checklist',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'Rr5utB7OFsI',
    title: 'Want to Become a Process Server in Oklahoma? — Complete 2026 Guide',
    description: 'Everything you need to know to become a licensed process server in Oklahoma — licensing, bonding, court registration, and building your business.',
    datePublished: '2026-04-01',
    duration: 'PT14M0S',
    relatedPage: '/blog/become-process-server-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: '7BxAu4S-q0k',
    title: 'Federal Court Process Serving in Oklahoma — Different Rules You Need to Know',
    description: 'Federal court process serving in Oklahoma follows different rules than state court. Learn what\'s required under FRCP Rule 4 and how we handle federal service.',
    datePublished: '2026-04-01',
    duration: 'PT11M0S',
    relatedPage: '/process-serving',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'Y-ATkdBkLsY',
    title: 'Protective Order & Restraining Order Service in Oklahoma',
    description: 'How protective orders and restraining orders are legally served in Oklahoma — VPO service, emergency orders, and documentation requirements.',
    datePublished: '2026-04-01',
    duration: 'PT10M0S',
    relatedPage: '/blog/how-to-file-protective-order-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'iuSq5CGC07w',
    title: 'Divorce & Family Law Process Serving in Oklahoma — Complete Guide',
    description: 'Complete guide to serving divorce papers and family law documents in Oklahoma — personal service, substituted service, and proof of service requirements.',
    datePublished: '2026-04-01',
    duration: 'PT13M0S',
    relatedPage: '/blog/how-to-serve-divorce-papers-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: '9fpWkN2l7xQ',
    title: 'Landlord\'s Complete Guide to Oklahoma Eviction Process Serving | Just Legal Solutions',
    description: 'A dedicated landlord\'s guide to properly serving eviction notices and FED (Forcible Entry and Detainer) summons in Oklahoma.',
    datePublished: '2026-04-01',
    duration: 'PT12M0S',
    relatedPage: '/blog/how-to-serve-eviction-notices-in-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'U9vTOLPoB7E',
    title: 'How to Get a Document Notarized in Oklahoma — Beginner\'s Guide | Just Legal Solutions',
    description: 'A beginner-friendly guide to getting documents notarized in Oklahoma — what to bring, how the process works, and what to expect.',
    datePublished: '2026-04-01',
    duration: 'PT9M0S',
    relatedPage: '/notary',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: '-C9XFE71nVU',
    title: 'New Oklahoma Notary Laws 2026 — HB 2265 Changes Explained',
    description: 'What changed for Oklahoma notaries in 2026 under HB 2265 — new requirements, updated journal rules, and what notaries must do to stay compliant.',
    datePublished: '2026-04-01',
    duration: 'PT11M0S',
    relatedPage: '/notary-laws',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'UTU0Xtpps3I',
    title: 'How to Get an Apostille in Oklahoma — Step by Step Guide',
    description: 'Step-by-step guide to obtaining an apostille in Oklahoma for international document use — what it is, who issues it, and how long it takes.',
    datePublished: '2026-04-01',
    duration: 'PT10M0S',
    relatedPage: '/notary',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'q5JlBEFCUlU',
    title: 'Subpoena Service in Oklahoma | Witness & Document Subpoenas Explained',
    description: 'Everything you need to know about serving witness subpoenas and document subpoenas in Oklahoma civil and criminal cases.',
    datePublished: '2026-04-01',
    duration: 'PT11M0S',
    relatedPage: '/blog/how-to-serve-a-subpoena-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'qDey9Ihtpys',
    title: 'Small Claims Court Process Serving Oklahoma | Complete Guide to Filing & Serving',
    description: 'Complete guide to filing and serving small claims court papers in Oklahoma — from filing your petition to serving the defendant and attending your hearing.',
    datePublished: '2026-04-01',
    duration: 'PT12M0S',
    relatedPage: '/blog/how-to-serve-small-claims-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'tEASEYhCM1o',
    title: 'Substitute Service in Oklahoma | When Personal Service Fails — Your Legal Options',
    description: 'When personal service isn\'t possible in Oklahoma, substitute service under 12 O.S. § 2004(C)(1) may be your answer. Learn how it works and when courts approve it.',
    datePublished: '2026-04-01',
    duration: 'PT10M0S',
    relatedPage: '/blog/substitute-service-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'g8-RXySoohc',
    title: 'How to Serve a Business or Corporation in Oklahoma | Corporate Process Serving Guide',
    description: 'How to properly serve a business entity, LLC, or corporation with legal papers in Oklahoma — registered agents, officers, and what happens when no agent is found.',
    datePublished: '2026-04-01',
    duration: 'PT11M0S',
    relatedPage: '/blog/serve-business-corporation-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'HLO7mJvNxG4',
    title: 'What To Do After Being Served Papers in Oklahoma | Your Rights Explained Step by Step',
    description: 'If you\'ve just been served with legal papers in Oklahoma, don\'t panic. This video walks you through exactly what to do next, your rights, and your deadlines.',
    datePublished: '2026-04-01',
    duration: 'PT10M0S',
    relatedPage: '/blog/what-to-do-when-served-papers-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'YpUtDJdS-WQ',
    title: 'Real Estate Closing & Loan Signing in Oklahoma — Mobile Notary Guide',
    description: 'Buying or selling a home in Oklahoma? Refinancing? Everything you need to know about real estate closings, loan signing agents, and mobile notary services for property transactions.',
    datePublished: '2026-04-13',
    duration: 'PT12M0S',
    relatedPage: '/real-estate-notary',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'ob4iQ-iPlpU',
    title: 'Debt Collection Process Serving in Oklahoma — Creditor\'s Guide',
    description: 'Creditors, collection agencies & attorneys: proper process serving is the foundation of every debt recovery case. Learn how to serve debt collection documents correctly in Oklahoma.',
    datePublished: '2026-04-13',
    duration: 'PT11M0S',
    relatedPage: '/process-serving-for-debt-collection',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'RWmgeCJ502U',
    title: 'Process Server vs Sheriff in Oklahoma — Which Should You Choose?',
    description: 'Need legal documents served in Oklahoma? You have two options: hire a private process server or use the county sheriff. An honest comparison of both options.',
    datePublished: '2026-04-13',
    duration: 'PT10M0S',
    relatedPage: '/blog/sheriff-vs-private-process-server-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'bzlgKgUfEtI',
    title: 'What Happens If You Avoid Being Served in Oklahoma? (The Truth)',
    description: 'Think you can dodge a process server? Think again. This video covers what really happens when you avoid service in Oklahoma — from alternative service methods to default judgments.',
    datePublished: '2026-04-13',
    duration: 'PT9M0S',
    relatedPage: '/what-happens-if-someone-refuses-service',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'ZHAQ3ziUaHw',
    title: 'Power of Attorney in Oklahoma — Types, Requirements & Complete Guide',
    description: 'Need a Power of Attorney in Oklahoma? This complete guide covers all 4 types — General, Durable, Healthcare & Limited — plus Oklahoma-specific requirements and notarization rules.',
    datePublished: '2026-04-13',
    duration: 'PT13M0S',
    relatedPage: '/power-of-attorney-notary-oklahoma',
    category: 'Featured',
    isShort: false,
  },
  {
    videoId: 'P8doTW8k3YU',
    title: 'Service by Publication in Oklahoma — Complete Step-by-Step Guide',
    description: 'Can\'t find someone to serve them? Oklahoma law provides a last resort: service by publication. Exactly when you can use it, the court requirements, and how to do it right.',
    datePublished: '2026-04-13',
    duration: 'PT11M0S',
    relatedPage: '/blog/oklahoma-service-by-publication',
    category: 'Featured',
    isShort: false,
  },
];

export const fullVideos: Video[] = [
  {
    videoId: 'PBCQDHACoi8',
    title: 'Process Server vs Sheriff Oklahoma (Which Is Better 2026)',
    description:
      'Joseph Iannazzi compares private process servers vs. sheriff service in Oklahoma — speed, cost, flexibility, and legal requirements explained for 2026.',
    datePublished: '2026-03-01',
    duration: 'PT8M0S',
    relatedPage: '/blog/sheriff-vs-private-process-server-oklahoma',
    category: 'Process Serving',
    isShort: false,
  },
  {
    videoId: '2oG6oM94G8I',
    title: 'What To Bring To Your Mobile Notary Appointment — Oklahoma Guide 2026',
    description:
      'Everything you need to bring to a mobile notary appointment in Oklahoma: valid ID, documents, witnesses, and more. Avoid common mistakes.',
    datePublished: '2026-03-05',
    duration: 'PT6M30S',
    relatedPage: '/what-to-bring',
    category: 'Notary',
    isShort: false,
  },
  {
    videoId: '9Bogug5UdqQ',
    title: 'Oklahoma Process Server Laws Explained — Legal Guide 2026',
    description:
      'A full breakdown of Oklahoma process server licensing requirements, statutes (12 O.S. § 158.1), and compliance rules for 2026.',
    datePublished: '2026-03-08',
    duration: 'PT10M0S',
    relatedPage: '/oklahoma-process-server-laws',
    category: 'Process Serving',
    isShort: false,
  },
  {
    videoId: 'FiLQQukVOBc',
    title: 'Remote Online Notary Oklahoma — Legal in 2026',
    description:
      'Is remote online notarization (RON) legal in Oklahoma in 2026? Joseph explains the laws, platforms, and how to get documents notarized entirely online.',
    datePublished: '2026-03-12',
    duration: 'PT7M0S',
    relatedPage: '/remote-online-notary',
    category: 'Notary',
    isShort: false,
  },
  {
    videoId: 'NFAhglMUNqc',
    title: 'Best Process Server in Tulsa, Oklahoma',
    description:
      'Why Just Legal Solutions is Tulsa\'s top-rated process server — 156+ five-star reviews, GPS-tracked service, flat-rate pricing, and 24/7 emergency availability.',
    datePublished: '2026-03-15',
    duration: 'PT5M0S',
    relatedPage: '/tulsa-process-server',
    category: 'Process Serving',
    isShort: false,
  },
  {
    videoId: 'zTuTJiO71Gk',
    title: 'How Much Does a Process Server Cost in Oklahoma? — Full 2026 Pricing Breakdown',
    description:
      'Complete 2026 pricing guide for Oklahoma process serving: standard $60, rush $150, same-day $265. No mileage fees, no hidden charges across all 77 counties.',
    datePublished: '2026-03-20',
    duration: 'PT9M0S',
    relatedPage: '/how-much-does-process-server-cost',
    category: 'Pricing',
    isShort: false,
  },
];

export const shorts: Video[] = [
  {
    videoId: 'FA1k11n2MNc',
    title: 'Rush & Same-Day Process Serving Tulsa Oklahoma 2026',
    description: 'Need papers served fast? See how rush and same-day process serving works in Tulsa, Oklahoma.',
    datePublished: '2026-03-02',
    duration: 'PT60S',
    relatedPage: '/rush-vs-standard-vs-same-day-service',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'MyLClwwuewY',
    title: 'Wedding Officiant Services Tulsa Oklahoma 2026',
    description: 'Joseph is a licensed wedding officiant in Oklahoma — legal ceremonies, elopements, and civil unions.',
    datePublished: '2026-03-02',
    duration: 'PT60S',
    relatedPage: '/wedding-officiant',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'av9_-Gr81MQ',
    title: 'Immigration Document Notary Oklahoma Requirements 2026',
    description: 'What immigration documents require notarization in Oklahoma, and what to bring to your appointment.',
    datePublished: '2026-03-03',
    duration: 'PT60S',
    relatedPage: '/immigration-document-notary-oklahoma',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: '7FYC5Uh8BqE',
    title: 'Real Estate Closing Notary Tulsa Oklahoma — Signing Agent 2026',
    description: 'What a loan signing agent does at real estate closings in Tulsa, Oklahoma.',
    datePublished: '2026-03-03',
    duration: 'PT60S',
    relatedPage: '/real-estate-notary',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: '-I2yhHi5m0E',
    title: 'Loan Signing Agent Oklahoma — What They Do 2026',
    description: 'Difference between a notary and a certified loan signing agent in Oklahoma.',
    datePublished: '2026-03-04',
    duration: 'PT60S',
    relatedPage: '/loan-signing-agent-tulsa',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'l-2Pw4ZY9z4',
    title: 'Hospital Notary Services Oklahoma — Medical Legal Documents 2026',
    description: 'How mobile notary services work in hospitals, hospice facilities, and care centers in Oklahoma.',
    datePublished: '2026-03-04',
    duration: 'PT60S',
    relatedPage: '/hospital-notary',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'mVm-yPjIJog',
    title: 'Power of Attorney Notary Oklahoma — Step by Step Guide 2026',
    description: 'How to get a Power of Attorney notarized in Oklahoma step by step.',
    datePublished: '2026-03-05',
    duration: 'PT60S',
    relatedPage: '/power-of-attorney-notary-oklahoma',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'OlljbiBmPEI',
    title: 'Mobile Notary vs Bank Notary Oklahoma — Comparison 2026',
    description: 'Mobile notary vs bank notary: which is better for your situation in Oklahoma?',
    datePublished: '2026-03-06',
    duration: 'PT60S',
    relatedPage: '/mobile-notary-vs-bank',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'XNkr7tAh3R0',
    title: 'What Is a Mobile Notary? — Oklahoma Notary Services 2026',
    description: 'What a mobile notary does, how to hire one, and when you need one in Oklahoma.',
    datePublished: '2026-03-06',
    duration: 'PT60S',
    relatedPage: '/mobile-notary',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'w7MLnkKUaXw',
    title: 'Debt Collection Process Serving Oklahoma Tulsa Legal 2026',
    description: 'How process serving works for debt collection cases in Oklahoma — serving summons and complaints.',
    datePublished: '2026-03-07',
    duration: 'PT60S',
    relatedPage: '/process-serving-for-debt-collection',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'e6OCpIZVC-A',
    title: 'GPS-Tracked Process Serving Oklahoma — Why It Matters 2026',
    description: 'Why GPS-verified process serving creates court-proof documentation that holds up to challenges in Oklahoma.',
    datePublished: '2026-03-08',
    duration: 'PT60S',
    relatedPage: '/gps-tracked-process-serving',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'Jpk6tOjEnVs',
    title: 'Cannot Find Someone to Serve? — Oklahoma Skip Tracing 2026',
    description: 'What happens when you can\'t find someone to serve in Oklahoma — skip tracing explained.',
    datePublished: '2026-03-09',
    duration: 'PT60S',
    relatedPage: '/ai-skip-tracing-guide-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'ROZiEmxx33k',
    title: 'Eviction Process Serving Tulsa Oklahoma — Legal Guide 2026',
    description: 'How eviction notices are legally served in Oklahoma — Forcible Entry and Detainer rules.',
    datePublished: '2026-03-10',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-serve-eviction-notices-in-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'cZfshhpPQYY',
    title: 'Divorce Process Serving Oklahoma Tulsa Legal Guide 2026',
    description: 'How to serve divorce papers in Oklahoma — legal requirements under 12 O.S. § 2004.',
    datePublished: '2026-03-11',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-serve-divorce-papers-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'BXO_ga6zhKA',
    title: 'Sunday Process Serving Oklahoma — Legal or Not? 2026',
    description: 'Can a process server serve papers on Sunday in Oklahoma? The answer might surprise you.',
    datePublished: '2026-03-12',
    duration: 'PT60S',
    relatedPage: '/can-process-server-serve-on-sunday',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: '6TibSVogOeE',
    title: 'Process Server Cost Tulsa Oklahoma — Pricing Guide 2026',
    description: 'How much does a process server cost in Tulsa? Standard, rush, and same-day pricing explained.',
    datePublished: '2026-03-13',
    duration: 'PT60S',
    relatedPage: '/oklahoma-process-server-pricing',
    category: 'Pricing',
    isShort: true,
  },
  {
    videoId: 'yadgfypxTu0',
    title: 'How Long Does Process Serving Take? — Oklahoma Timeline 2026',
    description: 'Standard, rush, and same-day process serving timelines in Oklahoma — what to expect.',
    datePublished: '2026-03-14',
    duration: 'PT60S',
    relatedPage: '/how-long-does-process-serving-take',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: '9Ow7-muHxl8',
    title: 'What Happens If Someone Avoids Service? — Tulsa Process Server',
    description: 'What happens when someone tries to avoid being served in Oklahoma — skip tracing, drop service, and legal options.',
    datePublished: '2026-03-15',
    duration: 'PT60S',
    relatedPage: '/what-happens-if-someone-refuses-service',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'cbHsAUozxnc',
    title: 'How Process Serving Works in Oklahoma 2026 — Tulsa Legal',
    description: 'The full process serving workflow in Oklahoma explained — from filing to affidavit of service.',
    datePublished: '2026-03-16',
    duration: 'PT60S',
    relatedPage: '/process-server-tulsa-guide',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'wqPJSh_RABc',
    title: 'How Much Does a Process Server Cost in Oklahoma?',
    description: 'Quick breakdown of process server pricing in Oklahoma — no hidden fees, all 77 counties covered.',
    datePublished: '2026-03-17',
    duration: 'PT60S',
    relatedPage: '/how-much-does-process-server-cost',
    category: 'Pricing',
    isShort: true,
  },
  {
    videoId: 'UvaLxZVVfQ0',
    title: 'Stillwater Process Server',
    description: 'Need a process server in Stillwater? Fast, GPS-tracked legal document delivery in Payne County.',
    datePublished: '2026-04-25',
    duration: 'PT60S',
    relatedPage: '/service-areas/stillwater',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'NWEgQRl_ibg',
    title: 'What Is a Subpoena?',
    description: 'Quick explanation of what a subpoena is, when it is used, and how legal service works in Oklahoma.',
    datePublished: '2026-04-25',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-serve-a-subpoena-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'wkr5KRZEFwM',
    title: 'Muskogee Process Server',
    description: 'Professional process serving in Muskogee County with reliable, court-ready proof of service.',
    datePublished: '2026-04-25',
    duration: 'PT60S',
    relatedPage: '/service-areas/muskogee',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: '3-GEE8s0hIU',
    title: 'What Is Substitute Service',
    description: 'What substitute service means in Oklahoma and when courts may allow alternatives to personal service.',
    datePublished: '2026-04-25',
    duration: 'PT60S',
    relatedPage: '/blog/substitute-service-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'ZcsBc8c__FE',
    title: 'Handling Evasive Defendants',
    description: 'How process servers handle evasive defendants using legal, documented methods in Oklahoma.',
    datePublished: '2026-04-25',
    duration: 'PT60S',
    relatedPage: '/what-happens-if-someone-refuses-service',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'qJ0D0aKxgJk',
    title: 'How to Serve Divorce Papers',
    description: 'The basic steps for properly serving divorce papers in Oklahoma family law cases.',
    datePublished: '2026-04-25',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-serve-divorce-papers-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'GuRCD8TOv-c',
    title: 'Serve Eviction Notices',
    description: 'How eviction notices are served in Oklahoma and why proper service is critical for court.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-serve-eviction-notices-in-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'okhDX_BpwmM',
    title: 'Service by Publication',
    description: 'When service by publication is allowed in Oklahoma and what the court requires.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/oklahoma-service-by-publication',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'CrKAoZKWz6c',
    title: 'Serve Small Claims',
    description: 'How to serve defendants in Oklahoma small claims cases with valid proof of service.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-serve-small-claims-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'OydpIeoBOI0',
    title: 'Serve Restraining Order',
    description: 'How protective and restraining orders are legally served in Oklahoma.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-file-protective-order-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'nDEGmFhrkhw',
    title: 'DIY vs Professional',
    description: 'DIY service vs hiring a professional process server: cost, risk, and legal outcomes.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/diy-vs-professional-service-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'Zokcztn-Kak',
    title: 'Sheriff vs Private',
    description: 'Sheriff service vs private process server in Oklahoma: speed, pricing, and reliability.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/sheriff-vs-private-process-server-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: '2nOYpwu911s',
    title: 'Contest Improper Service',
    description: 'How improper service gets challenged and what documentation protects your case.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/contest-improper-service-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'jGxc4JErkhI',
    title: 'Default Judgment',
    description: 'How default judgment works when defendants fail to respond after valid service.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/oklahoma-default-judgment-guide',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'E4PlhsKquak',
    title: 'How Long to Respond',
    description: 'How long someone has to respond after being served in Oklahoma civil cases.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/how-long-respond-lawsuit-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'RrojLYtbeAo',
    title: 'Proof of Service',
    description: 'What proof of service includes and why affidavit accuracy matters in court.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/understanding-the-affidavit-of-service',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'mWEeJ77Ws3U',
    title: 'Serve a Business',
    description: 'How to serve an LLC or corporation in Oklahoma through agents and legal officers.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/serve-business-corporation-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'UIWunTVg1Nw',
    title: 'Child Custody & Support',
    description: 'Process serving considerations in Oklahoma child custody and child support cases.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'VNdqQrDx8yg',
    title: 'File Protective Order',
    description: 'How to file and serve a protective order in Oklahoma, including urgent timing tips.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-file-protective-order-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'MjSMooL-bHg',
    title: 'Landlord Eviction Timelines',
    description: 'Typical Oklahoma landlord eviction timelines and where process service fits.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/oklahoma-landlord-tenant-eviction-timelines',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'Vc8klQtB1X4',
    title: 'Loan Signing Agent',
    description: 'What a loan signing agent does in Oklahoma and when one is needed.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/loan-signing-agent-tulsa',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'C01tCn87fsk',
    title: 'Estate Planning Notarization',
    description: 'Estate planning documents that commonly require notarization in Oklahoma.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'kHU05c640Zg',
    title: 'Notary Fees',
    description: 'Quick overview of common Oklahoma notary fee limits and service costs.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/oklahoma-notary-fees-guide',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: '_g3VyTUZuPY',
    title: 'Power of Attorney',
    description: 'Power of attorney basics in Oklahoma and when notarization is required.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/power-of-attorney-notary-oklahoma',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'I4QnkueJUvU',
    title: 'Apostille Documents',
    description: 'What apostille documents are and how Oklahoma residents can get one.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/notary',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'O54QsZXYFPE',
    title: 'Day in Life Process Server',
    description: 'A quick look at a real day in the life of an Oklahoma process server.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: '8T__84fn7CQ',
    title: 'Bail Bondsmen & Process Servers',
    description: 'How bail bondsmen and process servers work together on time-sensitive cases.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/bail-bondsmen-process-serving',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'nkn6HV_dbhA',
    title: 'Bankruptcy Process Serving',
    description: 'Key process serving considerations in bankruptcy-related legal actions.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: '_zCEr88Aqhg',
    title: 'Banks & Lenders Process Serving',
    description: 'How process serving supports banks and lenders in Oklahoma legal matters.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/banks-lenders-process-serving-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'eYG5f_nyLS4',
    title: 'Become a Process Server',
    description: 'How to become a licensed process server in Oklahoma, step by step.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/become-process-server-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'nK9HAyj9zag',
    title: 'Notarize for Family?',
    description: 'Can you notarize documents for family members in Oklahoma? Quick legal answer.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'eM1OyDtmMoc',
    title: 'Electronic Notarization (RON)',
    description: 'How remote online notarization (RON) works in Oklahoma for eligible documents.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/remote-online-notary',
    category: 'Notary',
    isShort: true,
  },
  {
    videoId: 'vgHwwgCsK38',
    title: 'January Process Serving Surge',
    description: 'Why process serving demand often spikes in January and early Q1.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/january-process-serving-spike-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'NMTgDl-vsL8',
    title: 'Eviction Moratorium History',
    description: 'A quick timeline of eviction moratorium history and legal impact in Oklahoma.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/oklahoma-eviction-moratorium-history',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'HYhui6OBtHQ',
    title: 'Healthcare/Hospital Serving',
    description: 'Process serving considerations in healthcare and hospital environments.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'ct8-V3MbgxQ',
    title: 'HOA Process Serving',
    description: 'How process serving supports HOA-related legal actions and compliance cases.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'XKRuREq84PU',
    title: 'Oil & Gas Process Serving',
    description: 'Process serving for oil and gas litigation, disputes, and notices in Oklahoma.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'MzwLtBbKuPw',
    title: 'Small Business Process Serving',
    description: 'How small businesses use process serving for legal notices and claims.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/process-serving-small-business-owners-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'Ubh7PAK5OFs',
    title: 'Real Estate Process Serving',
    description: 'Real estate litigation and notice delivery process serving in Oklahoma.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'lMQfc28K694',
    title: 'Serving Out-of-State Defendants',
    description: 'How Oklahoma cases can serve out-of-state defendants using valid legal methods.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/serve-out-of-state-defendant-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'DE3IlaZZ5HQ',
    title: 'Serving Government Entities',
    description: 'Special service rules when serving state, county, or municipal government entities.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/serving-government-entities-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'bHLMCTYjMwU',
    title: 'Tax Season Legal Actions',
    description: 'How tax season often increases legal filings and process serving volume.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'zR3lvWmpbzw',
    title: 'Tulsa Court Filing Guide',
    description: 'Quick guide to court filing workflow and service coordination in Tulsa.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/tulsa-court-filing-guide',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'cibk7WWfXao',
    title: 'How to Hire a Process Server',
    description: 'What to look for when hiring a process server in Oklahoma.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/blog/how-to-hire-a-process-server-oklahoma',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: 'FtzcPGDmOnw',
    title: 'Lawton (Comanche County)',
    description: 'Need a process server in Lawton? Local coverage for Comanche County legal service.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/service-areas/lawton',
    category: 'Process Serving',
    isShort: true,
  },
  {
    videoId: '55_ZMkfaNec',
    title: 'Tahlequah (Cherokee County)',
    description: 'Process serving coverage in Tahlequah and Cherokee County, Oklahoma.',
    datePublished: '2026-04-26',
    duration: 'PT60S',
    relatedPage: '/service-areas/tahlequah',
    category: 'Process Serving',
    isShort: true,
  },
];

export const seoShorts: Video[] = shorts.map(normalizeShortSeo);
export const allVideos = [...featuredVideos, ...fullVideos, ...seoShorts];



// Pre-computed O(1) caches for performance optimization
// Replaces O(N) array filtering/finding which is a bottleneck on large datasets during static generation
export const videoBySlugCache = new Map<string, Video>();
export const videoSlugByIdCache = new Map<string, string>();

for (const video of allVideos) {
  const slug = video.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
  videoBySlugCache.set(slug, video);
  videoSlugByIdCache.set(video.videoId, slug);
}

export function getVideoSlug(videoId: string): string {
  return videoSlugByIdCache.get(videoId) || videoId;
}

export function getVideoBySlug(slug: string): Video | undefined {
  return videoBySlugCache.get(slug);
}
