name: SEO Content Freshness

on:
  schedule:
    # Run every day at 1 AM UTC (automatically updates content daily)
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update sitemap timestamp
      run: |
        # Update static sitemap with current date
        current_date=$(date +%Y-%m-%d)
        sed -i "s/<lastmod>[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}<\/lastmod>/<lastmod>$current_date<\/lastmod>/g" public/sitemap.xml
        echo "Updated sitemap with date: $current_date"
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/sitemap.xml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-update: Refresh sitemap timestamp for SEO - $(date +%Y-%m-%d)"
          git push
          echo "Changes committed and pushed"
        fi
    
    - name: Build and test
      run: |
        npm run build
        echo "Build successful - SEO content is fresh!"
        
    - name: Create deployment trigger
      if: success()
      run: |
        echo "Content updated successfully on $(date)"
        echo "Sitemap freshness: ✅"
        echo "Dynamic API routes: ✅"
        echo "SEO optimization: ✅"
